/***********************************************************************************************************************************
Manifest Info Handler
***********************************************************************************************************************************/
#ifndef INFO_INFOMANIFEST_H
#define INFO_INFOMANIFEST_H

STRING_DECLARE(INFO_MANIFEST_KEY_BACKUP_ARCHIVE_START_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_BACKUP_ARCHIVE_STOP_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_BACKUP_PRIOR_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_BACKUP_TIMESTAMP_START_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_BACKUP_TIMESTAMP_STOP_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_BACKUP_TYPE_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_OPT_ARCHIVE_CHECK_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_OPT_ARCHIVE_COPY_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_OPT_BACKUP_STANDBY_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_OPT_CHECKSUM_PAGE_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_OPT_COMPRESS_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_OPT_HARDLINK_STR);
STRING_DECLARE(INFO_MANIFEST_KEY_OPT_ONLINE_STR);

#endif
