/***********************************************************************************************************************************
Manifest Info Handler
***********************************************************************************************************************************/
#include "common/type/string.h"
#include "info/infoManifest.h"

/* CSHANG
These keys will replace the following perl keys:
MANIFEST_KEY_ARCHIVE_START and INFO_BACKUP_KEY_ARCHIVE_START
MANIFEST_KEY_ARCHIVE_STOP and INFO_BACKUP_KEY_ARCHIVE_STOP
MANIFEST_KEY_PRIOR and INFO_BACKUP_KEY_PRIOR
MANIFEST_KEY_TIMESTAMP_START and INFO_BACKUP_KEY_TIMESTAMP_START
MANIFEST_KEY_TIMESTAMP_STOP and INFO_BACKUP_KEY_TIMESTAMP_STOP
MANIFEST_KEY_TYPE and INFO_BACKUP_KEY_TYPE
-- options:
MANIFEST_KEY_BACKUP_STANDBY and INFO_BACKUP_KEY_BACKUP_STANDBY
MANIFEST_KEY_ARCHIVE_CHECK and INFO_BACKUP_KEY_ARCHIVE_CHECK
MANIFEST_KEY_ARCHIVE_COPY and INFO_BACKUP_KEY_ARCHIVE_COPY
MANIFEST_KEY_CHECKSUM_PAGE INFO_BACKUP_KEY_CHECKSUM_PAGE
MANIFEST_KEY_COMPRESS and INFO_BACKUP_KEY_COMPRESS
MANIFEST_KEY_HARDLINK and INFO_BACKUP_KEY_HARDLINK
MANIFEST_KEY_ONLINE and INFO_BACKUP_KEY_ONLINE
*/
STRING_EXTERN(INFO_MANIFEST_KEY_BACKUP_ARCHIVE_START_STR,           INFO_MANIFEST_KEY_BACKUP_ARCHIVE_START);
STRING_EXTERN(INFO_MANIFEST_KEY_BACKUP_ARCHIVE_STOP_STR,            INFO_MANIFEST_KEY_BACKUP_ARCHIVE_STOP);
STRING_EXTERN(INFO_MANIFEST_KEY_BACKUP_PRIOR_STR,                   INFO_MANIFEST_KEY_BACKUP_PRIOR);
STRING_EXTERN(INFO_MANIFEST_KEY_BACKUP_TIMESTAMP_START_STR,         INFO_MANIFEST_KEY_BACKUP_TIMESTAMP_START);
STRING_EXTERN(INFO_MANIFEST_KEY_BACKUP_TIMESTAMP_STOP_STR,          INFO_MANIFEST_KEY_BACKUP_TIMESTAMP_STOP);
STRING_EXTERN(INFO_MANIFEST_KEY_BACKUP_TYPE_STR,                    INFO_MANIFEST_KEY_BACKUP_TYPE);
STRING_EXTERN(INFO_MANIFEST_KEY_OPT_ARCHIVE_CHECK_STR,              INFO_MANIFEST_KEY_OPT_ARCHIVE_CHECK);
STRING_EXTERN(INFO_MANIFEST_KEY_OPT_ARCHIVE_COPY_STR,               INFO_MANIFEST_KEY_OPT_ARCHIVE_COPY);
STRING_EXTERN(INFO_MANIFEST_KEY_OPT_BACKUP_STANDBY_STR,             INFO_MANIFEST_KEY_OPT_BACKUP_STANDBY);
STRING_EXTERN(INFO_MANIFEST_KEY_OPT_CHECKSUM_PAGE_STR,              INFO_MANIFEST_KEY_OPT_CHECKSUM_PAGE);
STRING_EXTERN(INFO_MANIFEST_KEY_OPT_COMPRESS_STR,                   INFO_MANIFEST_KEY_OPT_COMPRESS);
STRING_EXTERN(INFO_MANIFEST_KEY_OPT_HARDLINK_STR,                   INFO_MANIFEST_KEY_OPT_HARDLINK);
STRING_EXTERN(INFO_MANIFEST_KEY_OPT_ONLINE_STR,                     INFO_MANIFEST_KEY_OPT_ONLINE);
