/***********************************************************************************************************************************
Manifest Info Handler
***********************************************************************************************************************************/
#ifndef INFO_INFOMANIFEST_H
#define INFO_INFOMANIFEST_H

STRING_DECLARE(INFO_MANIFEST_KEY_BACKUP_STANDBY_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_ARCHIVE_CHECK_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_ARCHIVE_COPY_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_ARCHIVE_START_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_ARCHIVE_STOP_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_CHECKSUM_PAGE_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_COMPRESS_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_HARDLINK_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_ONLINE_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_BACKUP_PRIOR_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_TIMESTAMP_START_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_TIMESTAMP_STOP_STR)
STRING_DECLARE(INFO_MANIFEST_KEY_TYPE_STR)

#endif
