# Cirrus CI Build Definitions
# ----------------------------------------------------------------------------------------------------------------------------------

# Build the branch if it is integration, a pull request, or ends in -ci/-cic (-cic targets only Cirrus CI)
only_if: $CIRRUS_BRANCH == 'integration' || $CIRRUS_PR != '' || $CIRRUS_BRANCH =~ '.*-ci$' || $CIRRUS_BRANCH =~ '.*-cic$'

# No auto-cancel on integration
auto_cancellation: $CIRRUS_BRANCH != 'integration'

# FreeBSD 12
# ----------------------------------------------------------------------------------------------------------------------------------
freebsd_12_task:
  freebsd_instance:
    image_family: freebsd-12-2
    cpu: 4
    memory: 4G

  install_script: pkg install -y bash git postgresql-libpqxx pkgconf libxml2 gmake perl5 libyaml p5-YAML-LibYAML rsync

  script:
    - true

  debug_script:
    - ls -lah ${CIRRUS_WORKING_DIR}
    - ls -lah ${CIRRUS_WORKING_DIR}/..
