/***********************************************************************************************************************************
PostgreSQL Version Interfaces

See postgres/interface/version.intern.h for documentation.
***********************************************************************************************************************************/
#include "build.auto.h"

/***********************************************************************************************************************************
PostgreSQL 9.0 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_90

#define CheckPoint                                                  CheckPoint_90
#define ControlFileData                                             ControlFileData_90
#define DBState                                                     DBState_90
#define DB_STARTUP                                                  DB_STARTUP_90
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_90
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_90
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_90
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_90
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_90
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_90
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_90
#define XLogPageHeaderData                                          XLogPageHeaderData_90
#define XLogRecPtr                                                  XLogRecPtr_90

#include "postgres/interface/version.intern.h"

PG_INTERFACE(090);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 9.1 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_91

#define CheckPoint                                                  CheckPoint_91
#define ControlFileData                                             ControlFileData_91
#define DBState                                                     DBState_91
#define DB_STARTUP                                                  DB_STARTUP_91
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_91
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_91
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_91
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_91
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_91
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_91
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_91
#define XLogPageHeaderData                                          XLogPageHeaderData_91
#define XLogRecPtr                                                  XLogRecPtr_91

#include "postgres/interface/version.intern.h"

PG_INTERFACE(091);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 9.2 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_92

#define CheckPoint                                                  CheckPoint_92
#define ControlFileData                                             ControlFileData_92
#define DBState                                                     DBState_92
#define DB_STARTUP                                                  DB_STARTUP_92
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_92
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_92
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_92
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_92
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_92
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_92
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_92
#define XLogPageHeaderData                                          XLogPageHeaderData_92
#define XLogRecPtr                                                  XLogRecPtr_92

#include "postgres/interface/version.intern.h"

PG_INTERFACE(092);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 9.3 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_93

#define CheckPoint                                                  CheckPoint_93
#define ControlFileData                                             ControlFileData_93
#define DBState                                                     DBState_93
#define DB_STARTUP                                                  DB_STARTUP_93
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_93
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_93
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_93
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_93
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_93
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_93
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_93
#define XLogPageHeaderData                                          XLogPageHeaderData_93
#define XLogRecPtr                                                  XLogRecPtr_93

#include "postgres/interface/version.intern.h"

PG_INTERFACE(093);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 9.4 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_94

#define CheckPoint                                                  CheckPoint_94
#define ControlFileData                                             ControlFileData_94
#define DBState                                                     DBState_94
#define DB_STARTUP                                                  DB_STARTUP_94
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_94
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_94
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_94
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_94
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_94
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_94
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_94
#define XLogPageHeaderData                                          XLogPageHeaderData_94
#define XLogRecPtr                                                  XLogRecPtr_94

#include "postgres/interface/version.intern.h"

PG_INTERFACE(094);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 9.5 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_95

#define CheckPoint                                                  CheckPoint_95
#define ControlFileData                                             ControlFileData_95
#define DBState                                                     DBState_95
#define DB_STARTUP                                                  DB_STARTUP_95
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_95
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_95
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_95
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_95
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_95
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_95
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_95
#define XLogPageHeaderData                                          XLogPageHeaderData_95
#define XLogRecPtr                                                  XLogRecPtr_95

#include "postgres/interface/version.intern.h"

PG_INTERFACE(095);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 9.6 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_96

#define CheckPoint                                                  CheckPoint_96
#define ControlFileData                                             ControlFileData_96
#define DBState                                                     DBState_96
#define DB_STARTUP                                                  DB_STARTUP_96
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_96
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_96
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_96
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_96
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_96
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_96
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_96
#define XLogPageHeaderData                                          XLogPageHeaderData_96
#define XLogRecPtr                                                  XLogRecPtr_96

#include "postgres/interface/version.intern.h"

PG_INTERFACE(096);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 10 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_10

#define CheckPoint                                                  CheckPoint_10
#define ControlFileData                                             ControlFileData_10
#define DBState                                                     DBState_10
#define DB_STARTUP                                                  DB_STARTUP_10
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_10
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_10
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_10
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_10
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_10
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_10
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_10
#define XLogPageHeaderData                                          XLogPageHeaderData_10
#define XLogRecPtr                                                  XLogRecPtr_10

#include "postgres/interface/version.intern.h"

PG_INTERFACE(100);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 11 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_11

#define CheckPoint                                                  CheckPoint_11
#define ControlFileData                                             ControlFileData_11
#define DBState                                                     DBState_11
#define DB_STARTUP                                                  DB_STARTUP_11
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_11
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_11
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_11
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_11
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_11
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_11
#define XLogPageHeaderData                                          XLogPageHeaderData_11
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_11
#define XLogRecPtr                                                  XLogRecPtr_11

#include "postgres/interface/version.intern.h"

PG_INTERFACE(110);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 12 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_12

#define CheckPoint                                                  CheckPoint_12
#define ControlFileData                                             ControlFileData_12
#define DBState                                                     DBState_12
#define DB_STARTUP                                                  DB_STARTUP_12
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_12
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_12
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_12
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_12
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_12
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_12
#define FullTransactionId                                           FullTransactionId_12
#define XLogPageHeaderData                                          XLogPageHeaderData_12
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_12
#define XLogRecPtr                                                  XLogRecPtr_12

#include "postgres/interface/version.intern.h"

PG_INTERFACE(120);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef FullTransactionId
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 13 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_13

#define CheckPoint                                                  CheckPoint_13
#define ControlFileData                                             ControlFileData_13
#define DBState                                                     DBState_13
#define DB_STARTUP                                                  DB_STARTUP_13
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_13
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_13
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_13
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_13
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_13
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_13
#define FullTransactionId                                           FullTransactionId_13
#define XLogPageHeaderData                                          XLogPageHeaderData_13
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_13
#define XLogRecPtr                                                  XLogRecPtr_13

#include "postgres/interface/version.intern.h"

PG_INTERFACE(130);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef FullTransactionId
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 14 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_14

#define CheckPoint                                                  CheckPoint_14
#define ControlFileData                                             ControlFileData_14
#define DBState                                                     DBState_14
#define DB_STARTUP                                                  DB_STARTUP_14
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_14
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_14
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_14
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_14
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_14
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_14
#define FullTransactionId                                           FullTransactionId_14
#define XLogPageHeaderData                                          XLogPageHeaderData_14
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_14
#define XLogRecPtr                                                  XLogRecPtr_14

#include "postgres/interface/version.intern.h"

PG_INTERFACE(140);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef FullTransactionId
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
PostgreSQL 15 Interface
***********************************************************************************************************************************/
#define PG_VERSION                                                  PG_VERSION_15

#define CheckPoint                                                  CheckPoint_15
#define ControlFileData                                             ControlFileData_15
#define DBState                                                     DBState_15
#define DB_STARTUP                                                  DB_STARTUP_15
#define DB_SHUTDOWNED                                               DB_SHUTDOWNED_15
#define DB_SHUTDOWNED_IN_RECOVERY                                   DB_SHUTDOWNED_IN_RECOVERY_15
#define DB_SHUTDOWNING                                              DB_SHUTDOWNING_15
#define DB_IN_CRASH_RECOVERY                                        DB_IN_CRASH_RECOVERY_15
#define DB_IN_ARCHIVE_RECOVERY                                      DB_IN_ARCHIVE_RECOVERY_15
#define DB_IN_PRODUCTION                                            DB_IN_PRODUCTION_15
#define FullTransactionId                                           FullTransactionId_15
#define XLogPageHeaderData                                          XLogPageHeaderData_15
#define XLogLongPageHeaderData                                      XLogLongPageHeaderData_15
#define XLogRecPtr                                                  XLogRecPtr_15

#include "postgres/interface/version.intern.h"

PG_INTERFACE(150);

#undef CheckPoint
#undef ControlFileData
#undef DBState
#undef DB_STARTUP
#undef DB_SHUTDOWNED
#undef DB_SHUTDOWNED_IN_RECOVERY
#undef DB_SHUTDOWNING
#undef DB_IN_CRASH_RECOVERY
#undef DB_IN_ARCHIVE_RECOVERY
#undef DB_IN_PRODUCTION
#undef FullTransactionId
#undef XLogPageHeaderData
#undef XLogLongPageHeaderData
#undef XLogRecPtr

#undef CATALOG_VERSION_NO
#undef PG_CONTROL_VERSION
#undef PG_VERSION
#undef XLOG_PAGE_MAGIC

#undef PG_INTERFACE_CONTROL_IS
#undef PG_INTERFACE_CONTROL
#undef PG_INTERFACE_CONTROL_VERSION
#undef PG_INTERFACE_WAL_IS
#undef PG_INTERFACE_WAL

/***********************************************************************************************************************************
Interface !!!
***********************************************************************************************************************************/
static const PgInterface pgInterface[] =
{
    {
        .version = PG_VERSION_15,

        .controlIs = pgInterfaceControlIs150,
        .control = pgInterfaceControl150,
        .controlVersion = pgInterfaceControlVersion150,

        .walIs = pgInterfaceWalIs150,
        .wal = pgInterfaceWal150,
    },
    {
        .version = PG_VERSION_14,

        .controlIs = pgInterfaceControlIs140,
        .control = pgInterfaceControl140,
        .controlVersion = pgInterfaceControlVersion140,

        .walIs = pgInterfaceWalIs140,
        .wal = pgInterfaceWal140,
    },
    {
        .version = PG_VERSION_13,

        .controlIs = pgInterfaceControlIs130,
        .control = pgInterfaceControl130,
        .controlVersion = pgInterfaceControlVersion130,

        .walIs = pgInterfaceWalIs130,
        .wal = pgInterfaceWal130,
    },
    {
        .version = PG_VERSION_12,

        .controlIs = pgInterfaceControlIs120,
        .control = pgInterfaceControl120,
        .controlVersion = pgInterfaceControlVersion120,

        .walIs = pgInterfaceWalIs120,
        .wal = pgInterfaceWal120,
    },
    {
        .version = PG_VERSION_11,

        .controlIs = pgInterfaceControlIs110,
        .control = pgInterfaceControl110,
        .controlVersion = pgInterfaceControlVersion110,

        .walIs = pgInterfaceWalIs110,
        .wal = pgInterfaceWal110,
    },
    {
        .version = PG_VERSION_10,

        .controlIs = pgInterfaceControlIs100,
        .control = pgInterfaceControl100,
        .controlVersion = pgInterfaceControlVersion100,

        .walIs = pgInterfaceWalIs100,
        .wal = pgInterfaceWal100,
    },
    {
        .version = PG_VERSION_96,

        .controlIs = pgInterfaceControlIs096,
        .control = pgInterfaceControl096,
        .controlVersion = pgInterfaceControlVersion096,

        .walIs = pgInterfaceWalIs096,
        .wal = pgInterfaceWal096,
    },
    {
        .version = PG_VERSION_95,

        .controlIs = pgInterfaceControlIs095,
        .control = pgInterfaceControl095,
        .controlVersion = pgInterfaceControlVersion095,

        .walIs = pgInterfaceWalIs095,
        .wal = pgInterfaceWal095,
    },
    {
        .version = PG_VERSION_94,

        .controlIs = pgInterfaceControlIs094,
        .control = pgInterfaceControl094,
        .controlVersion = pgInterfaceControlVersion094,

        .walIs = pgInterfaceWalIs094,
        .wal = pgInterfaceWal094,
    },
    {
        .version = PG_VERSION_93,

        .controlIs = pgInterfaceControlIs093,
        .control = pgInterfaceControl093,
        .controlVersion = pgInterfaceControlVersion093,

        .walIs = pgInterfaceWalIs093,
        .wal = pgInterfaceWal093,
    },
    {
        .version = PG_VERSION_92,

        .controlIs = pgInterfaceControlIs092,
        .control = pgInterfaceControl092,
        .controlVersion = pgInterfaceControlVersion092,

        .walIs = pgInterfaceWalIs092,
        .wal = pgInterfaceWal092,
    },
    {
        .version = PG_VERSION_91,

        .controlIs = pgInterfaceControlIs091,
        .control = pgInterfaceControl091,
        .controlVersion = pgInterfaceControlVersion091,

        .walIs = pgInterfaceWalIs091,
        .wal = pgInterfaceWal091,
    },
    {
        .version = PG_VERSION_90,

        .controlIs = pgInterfaceControlIs090,
        .control = pgInterfaceControl090,
        .controlVersion = pgInterfaceControlVersion090,

        .walIs = pgInterfaceWalIs090,
        .wal = pgInterfaceWal090,
    },
};
