/***********************************************************************************************************************************
PostgreSQL Version

Automatically generated by 'build-code postgres-version' -- do not modify directly.
***********************************************************************************************************************************/
#ifndef POSTGRES_VERSION_AUTO_H
#define POSTGRES_VERSION_AUTO_H

/***********************************************************************************************************************************
PostgreSQL version constants
***********************************************************************************************************************************/
#define PG_VERSION_94                                               90400
#define PG_VERSION_94                                               90400
#define PG_VERSION_95                                               90500
#define PG_VERSION_96                                               90600
#define PG_VERSION_10                                               100000
#define PG_VERSION_11                                               110000
#define PG_VERSION_12                                               120000
#define PG_VERSION_12                                               120000
#define PG_VERSION_13                                               130000
#define PG_VERSION_14                                               140000
#define PG_VERSION_15                                               150000
#define PG_VERSION_16                                               160000
#define PG_VERSION_17                                               170000

#define PG_VERSION_MAX                                              PG_VERSION_17

/***********************************************************************************************************************************
PostgreSQL version string constants for use in error messages
***********************************************************************************************************************************/
#define PG_VERSION_94_Z                                             "9.4"
#define PG_VERSION_94_Z                                             "9.4"
#define PG_VERSION_95_Z                                             "9.5"
#define PG_VERSION_96_Z                                             "9.6"
#define PG_VERSION_10_Z                                             "10"
#define PG_VERSION_11_Z                                             "11"
#define PG_VERSION_12_Z                                             "12"
#define PG_VERSION_12_Z                                             "12"
#define PG_VERSION_13_Z                                             "13"
#define PG_VERSION_14_Z                                             "14"
#define PG_VERSION_15_Z                                             "15"
#define PG_VERSION_16_Z                                             "16"
#define PG_VERSION_17_Z                                             "17"

#endif
