/***********************************************************************************************************************************
Cipher Info

Everything needed to encrypt or decrypt, kept together so that adding to it does not mean changing every function and protocol
message that carries it.

The pass is the bytes the key is derived from rather than the text it was stored as, so whoever reads it from the repository decides
how to read it and nothing downstream has to know. A key generated by pgBackRest is decoded to the bytes it encodes, while a
passphrase supplied by the user is the text it already is. The digest goes with the pass because the two are chosen together: a key
derives with SHA-256 and a passphrase with SHA-1, and which of those a repository uses depends on the format it was written at.

The pass is copied into the object so the caller is free to release whatever it was read from.
***********************************************************************************************************************************/
#ifndef COMMON_CRYPTO_INFO_H
#define COMMON_CRYPTO_INFO_H

/***********************************************************************************************************************************
Object type
***********************************************************************************************************************************/
typedef struct CipherInfo CipherInfo;

#include "common/crypto/common.h"
#include "common/type/buffer.h"
#include "common/type/object.h"
#include "common/type/pack.h"

/***********************************************************************************************************************************
Constructors
***********************************************************************************************************************************/
// Create for a repository that is not encrypted
FN_EXTERN CipherInfo *cipherInfoNewNone(void);

// Create from a pass, which is the key bytes or the passphrase text rather than what either was stored as
typedef struct CipherInfoNewParam
{
    VAR_PARAM_HEADER;
    HashType digest;                                                // Digest to use instead of the one duplicated
} CipherInfoNewParam;

#define cipherInfoNewP(type, pass, ...)                                                                                            \
    cipherInfoNew(type, pass, (CipherInfoNewParam){VAR_PARAM_INIT, __VA_ARGS__})

FN_EXTERN CipherInfo *cipherInfoNew(CipherType type, const Buffer *pass, CipherInfoNewParam param);

// Create from a pass as it is stored in the repository. A key carries a prefix and is decoded to the bytes it encodes, deriving
// with SHA-256. Anything else is a passphrase used as the text it already is, deriving with SHA-1. This is the only place that
// distinction is made, so nothing else needs to know how a pass was stored.
FN_EXTERN CipherInfo *cipherInfoNewStore(CipherType type, const String *pass);

// Create from a pack written by cipherInfoPack()
FN_EXTERN CipherInfo *cipherInfoNewPack(PackRead *packRead);

// Duplicate
FN_EXTERN CipherInfo *cipherInfoDup(const CipherInfo *this);

/***********************************************************************************************************************************
Getters/Setters
***********************************************************************************************************************************/
typedef struct CipherInfoPub
{
    CipherType type;                                                // Cipher type, none when not encrypted
    HashType digest;                                                // Digest the pass derives the key with
    const Buffer *pass;                                             // Passphrase text or key bytes
} CipherInfoPub;

// Cipher type
FN_INLINE_ALWAYS CipherType
cipherInfoType(const CipherInfo *const this)
{
    return THIS_PUB(CipherInfo)->type;
}

// Digest the pass derives the key with
FN_INLINE_ALWAYS HashType
cipherInfoDigest(const CipherInfo *const this)
{
    return THIS_PUB(CipherInfo)->digest;
}

// Passphrase text or key bytes
FN_INLINE_ALWAYS const Buffer *
cipherInfoPass(const CipherInfo *const this)
{
    return THIS_PUB(CipherInfo)->pass;
}

/***********************************************************************************************************************************
Functions
***********************************************************************************************************************************/
// Write to a pack so it can be passed over a protocol
FN_EXTERN void cipherInfoPack(PackWrite *packWrite, const CipherInfo *this);

// Move to a new parent mem context
FN_INLINE_ALWAYS CipherInfo *
cipherInfoMove(CipherInfo *const this, MemContext *const parentNew)
{
    return objMove(this, parentNew);
}

/***********************************************************************************************************************************
Destructor
***********************************************************************************************************************************/
FN_INLINE_ALWAYS void
cipherInfoFree(CipherInfo *const this)
{
    objFree(this);
}

/***********************************************************************************************************************************
Macros for function logging
***********************************************************************************************************************************/
FN_EXTERN void cipherInfoToLog(const CipherInfo *this, StringStatic *debugLog);

#define FUNCTION_LOG_CIPHER_INFO_TYPE                                                                                              \
    CipherInfo *
#define FUNCTION_LOG_CIPHER_INFO_FORMAT(value, buffer, bufferSize)                                                                 \
    FUNCTION_LOG_OBJECT_FORMAT(value, cipherInfoToLog, buffer, bufferSize)

#endif
