/***********************************************************************************************************************************
Command and Option Configuration

Automatically generated by Build.pm -- do not modify directly.
***********************************************************************************************************************************/

/***********************************************************************************************************************************
Command data
***********************************************************************************************************************************/
static ConfigCommandData configCommandData[CFG_COMMAND_TOTAL] = CONFIG_COMMAND_LIST
(
    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("archive-get")

        CONFIG_COMMAND_LOG_FILE(false)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("archive-push")

        CONFIG_COMMAND_LOG_FILE(false)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("backup")

        CONFIG_COMMAND_LOG_FILE(true)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("check")

        CONFIG_COMMAND_LOG_FILE(false)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("expire")

        CONFIG_COMMAND_LOG_FILE(true)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("help")

        CONFIG_COMMAND_LOG_FILE(false)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelDebug)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("info")

        CONFIG_COMMAND_LOG_FILE(false)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelDebug)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("local")

        CONFIG_COMMAND_LOG_FILE(false)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelError)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("remote")

        CONFIG_COMMAND_LOG_FILE(false)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelError)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("restore")

        CONFIG_COMMAND_LOG_FILE(true)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stanza-create")

        CONFIG_COMMAND_LOG_FILE(true)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stanza-delete")

        CONFIG_COMMAND_LOG_FILE(true)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stanza-upgrade")

        CONFIG_COMMAND_LOG_FILE(true)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("start")

        CONFIG_COMMAND_LOG_FILE(true)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stop")

        CONFIG_COMMAND_LOG_FILE(true)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelInfo)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("version")

        CONFIG_COMMAND_LOG_FILE(false)
        CONFIG_COMMAND_LOG_LEVEL_DEFAULT(logLevelDebug)
        CONFIG_COMMAND_LOG_LEVEL_STDERR_MAX(logLevelTrace)
    )
)

/***********************************************************************************************************************************
Option data
***********************************************************************************************************************************/
static ConfigOptionData configOptionData[CFG_OPTION_TOTAL] = CONFIG_OPTION_LIST
(
    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-async")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptArchiveAsync)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-check")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptArchiveCheck)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-copy")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptArchiveCopy)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-queue-max")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptArchiveQueueMax)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-timeout")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptArchiveTimeout)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-standby")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptBackupStandby)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("buffer-size")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptBufferSize)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("checksum-page")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptChecksumPage)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("cmd-ssh")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptCmdSsh)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("command")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptCommand)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptCompress)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress-level")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptCompressLevel)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress-level-network")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptCompressLevelNetwork)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("config")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-include")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptDbInclude)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-timeout")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptDbTimeout)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("delta")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptDelta)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("force")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptForce)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("host-id")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptHostId)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("link-all")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptLinkAll)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("link-map")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptLinkMap)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("lock-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptLockPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-console")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptLogLevelConsole)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-file")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptLogLevelFile)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-stderr")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptLogLevelStderr)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptLogPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-timestamp")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptLogTimestamp)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("manifest-save-threshold")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptManifestSaveThreshold)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("neutral-umask")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptNeutralUmask)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("online")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptOnline)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("output")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptOutput)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("perl-option")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPerlOption)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg1-host")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg2-host")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg3-host")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg4-host")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg5-host")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg6-host")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg7-host")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg8-host")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg1-host-cmd")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg2-host-cmd")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg3-host-cmd")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg4-host-cmd")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg5-host-cmd")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg6-host-cmd")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg7-host-cmd")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg8-host-cmd")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg1-host-config")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg2-host-config")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg3-host-config")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg4-host-config")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg5-host-config")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg6-host-config")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg7-host-config")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg8-host-config")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg1-host-port")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg2-host-port")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg3-host-port")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg4-host-port")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg5-host-port")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg6-host-port")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg7-host-port")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg8-host-port")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg1-host-user")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg2-host-user")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg3-host-user")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg4-host-user")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg5-host-user")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg6-host-user")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg7-host-user")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg8-host-user")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg1-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg2-path")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg3-path")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg4-path")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg5-path")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg6-path")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg7-path")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg8-path")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg1-port")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg2-port")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg3-port")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg4-port")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg5-port")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg6-port")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg7-port")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg8-port")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg1-socket-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg2-socket-path")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg3-socket-path")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg4-socket-path")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg5-socket-path")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg6-socket-path")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg7-socket-path")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("pg8-socket-path")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptPgSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("process")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptProcess)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("process-max")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptProcessMax)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("protocol-timeout")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptProtocolTimeout)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("recovery-option")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRecoveryOption)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-cipher-pass")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoCipherPass)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-cipher-type")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoCipherType)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-hardlink")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoHardlink)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-host")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-host-cmd")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoHostCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-host-config")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoHostConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-host-port")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoHostPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-host-user")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoHostUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-retention-archive")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoRetentionArchive)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-retention-archive-type")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoRetentionArchiveType)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-retention-diff")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoRetentionDiff)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-retention-full")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoRetentionFull)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-bucket")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3Bucket)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-ca-file")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3CaFile)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-ca-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3CaPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-endpoint")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3Endpoint)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-host")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3Host)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-key")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3Key)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-key-secret")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3KeySecret)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-region")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3Region)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-s3-verify-ssl")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoS3VerifySsl)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo1-type")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptRepoType)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("resume")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptResume)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("set")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptSet)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("spool-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptSpoolPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("stanza")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptStanza)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("start-fast")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptStartFast)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("stop-auto")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptStopAuto)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("tablespace-map")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTablespaceMap)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("tablespace-map-all")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTablespaceMapAll)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTarget)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-action")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTargetAction)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-exclusive")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTargetExclusive)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-timeline")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTargetTimeline)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTest)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test-delay")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTestDelay)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test-point")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptTestPoint)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("type")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_DEFINE_ID(cfgDefOptType)
    )
)
