/***********************************************************************************************************************************
Option Parse Definition

Automatically generated by Build.pm -- do not modify directly.
***********************************************************************************************************************************/

/***********************************************************************************************************************************
Option parse data
***********************************************************************************************************************************/
static const struct option optionList[] =
{
    // archive-async option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-async",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveAsync,
    },
    {
        .name = "no-archive-async",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveAsync,
    },
    {
        .name = "reset-archive-async",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveAsync,
    },

    // archive-check option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-check",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveCheck,
    },
    {
        .name = "no-archive-check",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveCheck,
    },
    {
        .name = "reset-archive-check",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveCheck,
    },

    // archive-copy option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-copy",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveCopy,
    },
    {
        .name = "no-archive-copy",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveCopy,
    },
    {
        .name = "reset-archive-copy",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveCopy,
    },

    // archive-get-queue-max option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-get-queue-max",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptArchiveGetQueueMax,
    },
    {
        .name = "reset-archive-get-queue-max",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveGetQueueMax,
    },

    // archive-mode option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-mode",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptArchiveMode,
    },
    {
        .name = "reset-archive-mode",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveMode,
    },

    // archive-push-queue-max option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-push-queue-max",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptArchivePushQueueMax,
    },
    {
        .name = "reset-archive-push-queue-max",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchivePushQueueMax,
    },
    {
        .name = "archive-queue-max",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptArchivePushQueueMax,
    },
    {
        .name = "reset-archive-queue-max",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | PARSE_RESET_FLAG | cfgOptArchivePushQueueMax,
    },

    // archive-timeout option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptArchiveTimeout,
    },
    {
        .name = "reset-archive-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveTimeout,
    },

    // backup-standby option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "backup-standby",
        .val = PARSE_OPTION_FLAG | cfgOptBackupStandby,
    },
    {
        .name = "no-backup-standby",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBackupStandby,
    },
    {
        .name = "reset-backup-standby",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptBackupStandby,
    },

    // buffer-size option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "buffer-size",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptBufferSize,
    },
    {
        .name = "reset-buffer-size",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptBufferSize,
    },

    // checksum-page option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "checksum-page",
        .val = PARSE_OPTION_FLAG | cfgOptChecksumPage,
    },
    {
        .name = "no-checksum-page",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptChecksumPage,
    },
    {
        .name = "reset-checksum-page",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptChecksumPage,
    },

    // cipher-pass option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "cipher-pass",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCipherPass,
    },

    // cmd-ssh option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "cmd-ssh",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCmdSsh,
    },
    {
        .name = "reset-cmd-ssh",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCmdSsh,
    },

    // compress option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "compress",
        .val = PARSE_OPTION_FLAG | cfgOptCompress,
    },
    {
        .name = "no-compress",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptCompress,
    },
    {
        .name = "reset-compress",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCompress,
    },

    // compress-level option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "compress-level",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCompressLevel,
    },
    {
        .name = "reset-compress-level",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCompressLevel,
    },

    // compress-level-network option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "compress-level-network",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCompressLevelNetwork,
    },
    {
        .name = "reset-compress-level-network",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCompressLevelNetwork,
    },

    // compress-type option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "compress-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCompressType,
    },
    {
        .name = "reset-compress-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCompressType,
    },

    // config option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptConfig,
    },
    {
        .name = "no-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptConfig,
    },

    // config-include-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptConfigIncludePath,
    },

    // config-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptConfigPath,
    },

    // db-include option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "db-include",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbInclude,
    },
    {
        .name = "reset-db-include",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptDbInclude,
    },

    // db-timeout option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "db-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbTimeout,
    },
    {
        .name = "reset-db-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptDbTimeout,
    },

    // delta option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "delta",
        .val = PARSE_OPTION_FLAG | cfgOptDelta,
    },
    {
        .name = "no-delta",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDelta,
    },
    {
        .name = "reset-delta",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptDelta,
    },

    // dry-run option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "dry-run",
        .val = PARSE_OPTION_FLAG | cfgOptDryRun,
    },

    // exclude option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "exclude",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptExclude,
    },
    {
        .name = "reset-exclude",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptExclude,
    },

    // expire-auto option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "expire-auto",
        .val = PARSE_OPTION_FLAG | cfgOptExpireAuto,
    },
    {
        .name = "no-expire-auto",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptExpireAuto,
    },
    {
        .name = "reset-expire-auto",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptExpireAuto,
    },

    // filter option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "filter",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptFilter,
    },

    // force option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "force",
        .val = PARSE_OPTION_FLAG | cfgOptForce,
    },

    // host-id option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "host-id",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptHostId,
    },

    // ignore-missing option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "ignore-missing",
        .val = PARSE_OPTION_FLAG | cfgOptIgnoreMissing,
    },

    // io-timeout option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "io-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptIoTimeout,
    },
    {
        .name = "reset-io-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptIoTimeout,
    },

    // link-all option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "link-all",
        .val = PARSE_OPTION_FLAG | cfgOptLinkAll,
    },
    {
        .name = "no-link-all",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLinkAll,
    },
    {
        .name = "reset-link-all",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLinkAll,
    },

    // link-map option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "link-map",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLinkMap,
    },
    {
        .name = "reset-link-map",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLinkMap,
    },

    // lock-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "lock-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLockPath,
    },
    {
        .name = "reset-lock-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLockPath,
    },

    // log-level-console option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-level-console",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelConsole,
    },
    {
        .name = "reset-log-level-console",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogLevelConsole,
    },

    // log-level-file option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-level-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelFile,
    },
    {
        .name = "reset-log-level-file",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogLevelFile,
    },

    // log-level-stderr option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-level-stderr",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelStderr,
    },
    {
        .name = "reset-log-level-stderr",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogLevelStderr,
    },

    // log-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogPath,
    },
    {
        .name = "reset-log-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogPath,
    },

    // log-subprocess option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-subprocess",
        .val = PARSE_OPTION_FLAG | cfgOptLogSubprocess,
    },
    {
        .name = "no-log-subprocess",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLogSubprocess,
    },
    {
        .name = "reset-log-subprocess",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogSubprocess,
    },

    // log-timestamp option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-timestamp",
        .val = PARSE_OPTION_FLAG | cfgOptLogTimestamp,
    },
    {
        .name = "no-log-timestamp",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLogTimestamp,
    },
    {
        .name = "reset-log-timestamp",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogTimestamp,
    },

    // manifest-save-threshold option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "manifest-save-threshold",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptManifestSaveThreshold,
    },
    {
        .name = "reset-manifest-save-threshold",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptManifestSaveThreshold,
    },

    // neutral-umask option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "neutral-umask",
        .val = PARSE_OPTION_FLAG | cfgOptNeutralUmask,
    },
    {
        .name = "no-neutral-umask",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptNeutralUmask,
    },
    {
        .name = "reset-neutral-umask",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptNeutralUmask,
    },

    // online option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "online",
        .val = PARSE_OPTION_FLAG | cfgOptOnline,
    },
    {
        .name = "no-online",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptOnline,
    },

    // output option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "output",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptOutput,
    },

    // pg-host option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHost,
    },
    {
        .name = "reset-pg1-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHost,
    },
    {
        .name = "db-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHost,
    },
    {
        .name = "db1-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHost,
    },
    {
        .name = "pg2-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 1),
    },
    {
        .name = "reset-pg2-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 1),
    },
    {
        .name = "db2-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 1),
    },
    {
        .name = "pg3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 2),
    },
    {
        .name = "reset-pg3-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 2),
    },
    {
        .name = "db3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 2),
    },
    {
        .name = "pg4-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 3),
    },
    {
        .name = "reset-pg4-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 3),
    },
    {
        .name = "db4-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 3),
    },
    {
        .name = "pg5-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 4),
    },
    {
        .name = "reset-pg5-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 4),
    },
    {
        .name = "db5-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 4),
    },
    {
        .name = "pg6-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 5),
    },
    {
        .name = "reset-pg6-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 5),
    },
    {
        .name = "db6-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 5),
    },
    {
        .name = "pg7-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 6),
    },
    {
        .name = "reset-pg7-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 6),
    },
    {
        .name = "db7-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 6),
    },
    {
        .name = "pg8-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 7),
    },
    {
        .name = "reset-pg8-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 7),
    },
    {
        .name = "db8-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 7),
    },

    // pg-host-cmd option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostCmd,
    },
    {
        .name = "reset-pg1-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostCmd,
    },
    {
        .name = "db-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostCmd,
    },
    {
        .name = "db1-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostCmd,
    },
    {
        .name = "pg2-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 1),
    },
    {
        .name = "reset-pg2-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 1),
    },
    {
        .name = "db2-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 1),
    },
    {
        .name = "pg3-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 2),
    },
    {
        .name = "reset-pg3-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 2),
    },
    {
        .name = "db3-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 2),
    },
    {
        .name = "pg4-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 3),
    },
    {
        .name = "reset-pg4-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 3),
    },
    {
        .name = "db4-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 3),
    },
    {
        .name = "pg5-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 4),
    },
    {
        .name = "reset-pg5-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 4),
    },
    {
        .name = "db5-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 4),
    },
    {
        .name = "pg6-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 5),
    },
    {
        .name = "reset-pg6-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 5),
    },
    {
        .name = "db6-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 5),
    },
    {
        .name = "pg7-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 6),
    },
    {
        .name = "reset-pg7-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 6),
    },
    {
        .name = "db7-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 6),
    },
    {
        .name = "pg8-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 7),
    },
    {
        .name = "reset-pg8-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 7),
    },
    {
        .name = "db8-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 7),
    },

    // pg-host-config option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostConfig,
    },
    {
        .name = "reset-pg1-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostConfig,
    },
    {
        .name = "db-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostConfig,
    },
    {
        .name = "db1-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostConfig,
    },
    {
        .name = "pg2-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 1),
    },
    {
        .name = "reset-pg2-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 1),
    },
    {
        .name = "db2-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 1),
    },
    {
        .name = "pg3-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 2),
    },
    {
        .name = "reset-pg3-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 2),
    },
    {
        .name = "db3-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 2),
    },
    {
        .name = "pg4-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 3),
    },
    {
        .name = "reset-pg4-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 3),
    },
    {
        .name = "db4-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 3),
    },
    {
        .name = "pg5-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 4),
    },
    {
        .name = "reset-pg5-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 4),
    },
    {
        .name = "db5-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 4),
    },
    {
        .name = "pg6-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 5),
    },
    {
        .name = "reset-pg6-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 5),
    },
    {
        .name = "db6-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 5),
    },
    {
        .name = "pg7-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 6),
    },
    {
        .name = "reset-pg7-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 6),
    },
    {
        .name = "db7-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 6),
    },
    {
        .name = "pg8-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 7),
    },
    {
        .name = "reset-pg8-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 7),
    },
    {
        .name = "db8-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 7),
    },

    // pg-host-config-include-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostConfigIncludePath,
    },
    {
        .name = "reset-pg1-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostConfigIncludePath,
    },
    {
        .name = "pg2-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigIncludePath + 1),
    },
    {
        .name = "reset-pg2-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigIncludePath + 1),
    },
    {
        .name = "pg3-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigIncludePath + 2),
    },
    {
        .name = "reset-pg3-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigIncludePath + 2),
    },
    {
        .name = "pg4-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigIncludePath + 3),
    },
    {
        .name = "reset-pg4-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigIncludePath + 3),
    },
    {
        .name = "pg5-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigIncludePath + 4),
    },
    {
        .name = "reset-pg5-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigIncludePath + 4),
    },
    {
        .name = "pg6-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigIncludePath + 5),
    },
    {
        .name = "reset-pg6-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigIncludePath + 5),
    },
    {
        .name = "pg7-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigIncludePath + 6),
    },
    {
        .name = "reset-pg7-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigIncludePath + 6),
    },
    {
        .name = "pg8-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigIncludePath + 7),
    },
    {
        .name = "reset-pg8-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigIncludePath + 7),
    },

    // pg-host-config-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostConfigPath,
    },
    {
        .name = "reset-pg1-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostConfigPath,
    },
    {
        .name = "pg2-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigPath + 1),
    },
    {
        .name = "reset-pg2-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigPath + 1),
    },
    {
        .name = "pg3-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigPath + 2),
    },
    {
        .name = "reset-pg3-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigPath + 2),
    },
    {
        .name = "pg4-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigPath + 3),
    },
    {
        .name = "reset-pg4-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigPath + 3),
    },
    {
        .name = "pg5-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigPath + 4),
    },
    {
        .name = "reset-pg5-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigPath + 4),
    },
    {
        .name = "pg6-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigPath + 5),
    },
    {
        .name = "reset-pg6-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigPath + 5),
    },
    {
        .name = "pg7-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigPath + 6),
    },
    {
        .name = "reset-pg7-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigPath + 6),
    },
    {
        .name = "pg8-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfigPath + 7),
    },
    {
        .name = "reset-pg8-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfigPath + 7),
    },

    // pg-host-port option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostPort,
    },
    {
        .name = "reset-pg1-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostPort,
    },
    {
        .name = "db-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostPort,
    },
    {
        .name = "db1-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostPort,
    },
    {
        .name = "pg2-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 1),
    },
    {
        .name = "reset-pg2-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 1),
    },
    {
        .name = "db2-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 1),
    },
    {
        .name = "pg3-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 2),
    },
    {
        .name = "reset-pg3-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 2),
    },
    {
        .name = "db3-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 2),
    },
    {
        .name = "pg4-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 3),
    },
    {
        .name = "reset-pg4-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 3),
    },
    {
        .name = "db4-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 3),
    },
    {
        .name = "pg5-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 4),
    },
    {
        .name = "reset-pg5-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 4),
    },
    {
        .name = "db5-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 4),
    },
    {
        .name = "pg6-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 5),
    },
    {
        .name = "reset-pg6-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 5),
    },
    {
        .name = "db6-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 5),
    },
    {
        .name = "pg7-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 6),
    },
    {
        .name = "reset-pg7-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 6),
    },
    {
        .name = "db7-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 6),
    },
    {
        .name = "pg8-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 7),
    },
    {
        .name = "reset-pg8-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 7),
    },
    {
        .name = "db8-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 7),
    },

    // pg-host-user option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostUser,
    },
    {
        .name = "reset-pg1-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostUser,
    },
    {
        .name = "db-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostUser,
    },
    {
        .name = "db1-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostUser,
    },
    {
        .name = "pg2-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 1),
    },
    {
        .name = "reset-pg2-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 1),
    },
    {
        .name = "db2-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 1),
    },
    {
        .name = "pg3-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 2),
    },
    {
        .name = "reset-pg3-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 2),
    },
    {
        .name = "db3-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 2),
    },
    {
        .name = "pg4-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 3),
    },
    {
        .name = "reset-pg4-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 3),
    },
    {
        .name = "db4-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 3),
    },
    {
        .name = "pg5-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 4),
    },
    {
        .name = "reset-pg5-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 4),
    },
    {
        .name = "db5-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 4),
    },
    {
        .name = "pg6-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 5),
    },
    {
        .name = "reset-pg6-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 5),
    },
    {
        .name = "db6-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 5),
    },
    {
        .name = "pg7-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 6),
    },
    {
        .name = "reset-pg7-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 6),
    },
    {
        .name = "db7-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 6),
    },
    {
        .name = "pg8-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 7),
    },
    {
        .name = "reset-pg8-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 7),
    },
    {
        .name = "db8-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 7),
    },

    // pg-local option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-local",
        .val = PARSE_OPTION_FLAG | cfgOptPgLocal,
    },
    {
        .name = "no-pg1-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptPgLocal,
    },
    {
        .name = "reset-pg1-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgLocal,
    },
    {
        .name = "pg2-local",
        .val = PARSE_OPTION_FLAG | (cfgOptPgLocal + 1),
    },
    {
        .name = "no-pg2-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptPgLocal + 1),
    },
    {
        .name = "reset-pg2-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgLocal + 1),
    },
    {
        .name = "pg3-local",
        .val = PARSE_OPTION_FLAG | (cfgOptPgLocal + 2),
    },
    {
        .name = "no-pg3-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptPgLocal + 2),
    },
    {
        .name = "reset-pg3-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgLocal + 2),
    },
    {
        .name = "pg4-local",
        .val = PARSE_OPTION_FLAG | (cfgOptPgLocal + 3),
    },
    {
        .name = "no-pg4-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptPgLocal + 3),
    },
    {
        .name = "reset-pg4-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgLocal + 3),
    },
    {
        .name = "pg5-local",
        .val = PARSE_OPTION_FLAG | (cfgOptPgLocal + 4),
    },
    {
        .name = "no-pg5-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptPgLocal + 4),
    },
    {
        .name = "reset-pg5-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgLocal + 4),
    },
    {
        .name = "pg6-local",
        .val = PARSE_OPTION_FLAG | (cfgOptPgLocal + 5),
    },
    {
        .name = "no-pg6-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptPgLocal + 5),
    },
    {
        .name = "reset-pg6-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgLocal + 5),
    },
    {
        .name = "pg7-local",
        .val = PARSE_OPTION_FLAG | (cfgOptPgLocal + 6),
    },
    {
        .name = "no-pg7-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptPgLocal + 6),
    },
    {
        .name = "reset-pg7-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgLocal + 6),
    },
    {
        .name = "pg8-local",
        .val = PARSE_OPTION_FLAG | (cfgOptPgLocal + 7),
    },
    {
        .name = "no-pg8-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptPgLocal + 7),
    },
    {
        .name = "reset-pg8-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgLocal + 7),
    },

    // pg-path option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgPath,
    },
    {
        .name = "reset-pg1-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgPath,
    },
    {
        .name = "db-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgPath,
    },
    {
        .name = "db1-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgPath,
    },
    {
        .name = "pg2-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 1),
    },
    {
        .name = "reset-pg2-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 1),
    },
    {
        .name = "db2-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 1),
    },
    {
        .name = "pg3-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 2),
    },
    {
        .name = "reset-pg3-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 2),
    },
    {
        .name = "db3-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 2),
    },
    {
        .name = "pg4-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 3),
    },
    {
        .name = "reset-pg4-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 3),
    },
    {
        .name = "db4-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 3),
    },
    {
        .name = "pg5-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 4),
    },
    {
        .name = "reset-pg5-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 4),
    },
    {
        .name = "db5-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 4),
    },
    {
        .name = "pg6-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 5),
    },
    {
        .name = "reset-pg6-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 5),
    },
    {
        .name = "db6-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 5),
    },
    {
        .name = "pg7-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 6),
    },
    {
        .name = "reset-pg7-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 6),
    },
    {
        .name = "db7-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 6),
    },
    {
        .name = "pg8-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 7),
    },
    {
        .name = "reset-pg8-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 7),
    },
    {
        .name = "db8-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 7),
    },

    // pg-port option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgPort,
    },
    {
        .name = "reset-pg1-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgPort,
    },
    {
        .name = "db-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgPort,
    },
    {
        .name = "db1-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgPort,
    },
    {
        .name = "pg2-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 1),
    },
    {
        .name = "reset-pg2-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 1),
    },
    {
        .name = "db2-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 1),
    },
    {
        .name = "pg3-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 2),
    },
    {
        .name = "reset-pg3-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 2),
    },
    {
        .name = "db3-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 2),
    },
    {
        .name = "pg4-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 3),
    },
    {
        .name = "reset-pg4-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 3),
    },
    {
        .name = "db4-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 3),
    },
    {
        .name = "pg5-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 4),
    },
    {
        .name = "reset-pg5-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 4),
    },
    {
        .name = "db5-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 4),
    },
    {
        .name = "pg6-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 5),
    },
    {
        .name = "reset-pg6-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 5),
    },
    {
        .name = "db6-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 5),
    },
    {
        .name = "pg7-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 6),
    },
    {
        .name = "reset-pg7-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 6),
    },
    {
        .name = "db7-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 6),
    },
    {
        .name = "pg8-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 7),
    },
    {
        .name = "reset-pg8-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 7),
    },
    {
        .name = "db8-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 7),
    },

    // pg-socket-path option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgSocketPath,
    },
    {
        .name = "reset-pg1-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgSocketPath,
    },
    {
        .name = "db-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgSocketPath,
    },
    {
        .name = "db1-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgSocketPath,
    },
    {
        .name = "pg2-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 1),
    },
    {
        .name = "reset-pg2-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 1),
    },
    {
        .name = "db2-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 1),
    },
    {
        .name = "pg3-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 2),
    },
    {
        .name = "reset-pg3-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 2),
    },
    {
        .name = "db3-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 2),
    },
    {
        .name = "pg4-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 3),
    },
    {
        .name = "reset-pg4-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 3),
    },
    {
        .name = "db4-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 3),
    },
    {
        .name = "pg5-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 4),
    },
    {
        .name = "reset-pg5-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 4),
    },
    {
        .name = "db5-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 4),
    },
    {
        .name = "pg6-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 5),
    },
    {
        .name = "reset-pg6-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 5),
    },
    {
        .name = "db6-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 5),
    },
    {
        .name = "pg7-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 6),
    },
    {
        .name = "reset-pg7-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 6),
    },
    {
        .name = "db7-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 6),
    },
    {
        .name = "pg8-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 7),
    },
    {
        .name = "reset-pg8-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 7),
    },
    {
        .name = "db8-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 7),
    },

    // pg-user option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgUser,
    },
    {
        .name = "reset-pg1-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgUser,
    },
    {
        .name = "pg2-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgUser + 1),
    },
    {
        .name = "reset-pg2-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgUser + 1),
    },
    {
        .name = "pg3-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgUser + 2),
    },
    {
        .name = "reset-pg3-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgUser + 2),
    },
    {
        .name = "pg4-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgUser + 3),
    },
    {
        .name = "reset-pg4-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgUser + 3),
    },
    {
        .name = "pg5-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgUser + 4),
    },
    {
        .name = "reset-pg5-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgUser + 4),
    },
    {
        .name = "pg6-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgUser + 5),
    },
    {
        .name = "reset-pg6-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgUser + 5),
    },
    {
        .name = "pg7-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgUser + 6),
    },
    {
        .name = "reset-pg7-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgUser + 6),
    },
    {
        .name = "pg8-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgUser + 7),
    },
    {
        .name = "reset-pg8-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgUser + 7),
    },

    // process option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "process",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProcess,
    },

    // process-max option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "process-max",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProcessMax,
    },
    {
        .name = "reset-process-max",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptProcessMax,
    },

    // protocol-timeout option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "protocol-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProtocolTimeout,
    },
    {
        .name = "reset-protocol-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptProtocolTimeout,
    },

    // raw option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "raw",
        .val = PARSE_OPTION_FLAG | cfgOptRaw,
    },

    // recovery-option option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "recovery-option",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRecoveryOption,
    },
    {
        .name = "reset-recovery-option",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRecoveryOption,
    },

    // recurse option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "recurse",
        .val = PARSE_OPTION_FLAG | cfgOptRecurse,
    },

    // remote-type option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "remote-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRemoteType,
    },

    // repo-azure-account option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-account",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureAccount,
    },
    {
        .name = "reset-repo1-azure-account",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureAccount,
    },

    // repo-azure-ca-file option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-ca-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureCaFile,
    },
    {
        .name = "reset-repo1-azure-ca-file",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureCaFile,
    },

    // repo-azure-ca-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-ca-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureCaPath,
    },
    {
        .name = "reset-repo1-azure-ca-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureCaPath,
    },

    // repo-azure-container option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-container",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureContainer,
    },
    {
        .name = "reset-repo1-azure-container",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureContainer,
    },

    // repo-azure-endpoint option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-endpoint",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureEndpoint,
    },
    {
        .name = "reset-repo1-azure-endpoint",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureEndpoint,
    },

    // repo-azure-host option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureHost,
    },
    {
        .name = "reset-repo1-azure-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureHost,
    },

    // repo-azure-key option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-key",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureKey,
    },
    {
        .name = "reset-repo1-azure-key",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureKey,
    },

    // repo-azure-key-type option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-key-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureKeyType,
    },
    {
        .name = "reset-repo1-azure-key-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureKeyType,
    },

    // repo-azure-port option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzurePort,
    },
    {
        .name = "reset-repo1-azure-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzurePort,
    },

    // repo-azure-verify-tls option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-azure-verify-tls",
        .val = PARSE_OPTION_FLAG | cfgOptRepoAzureVerifyTls,
    },
    {
        .name = "no-repo1-azure-verify-tls",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoAzureVerifyTls,
    },
    {
        .name = "reset-repo1-azure-verify-tls",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoAzureVerifyTls,
    },

    // repo-cipher-pass option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-cipher-pass",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoCipherPass,
    },
    {
        .name = "reset-repo1-cipher-pass",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoCipherPass,
    },
    {
        .name = "repo-cipher-pass",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoCipherPass,
    },

    // repo-cipher-type option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-cipher-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoCipherType,
    },
    {
        .name = "reset-repo1-cipher-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoCipherType,
    },
    {
        .name = "repo-cipher-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoCipherType,
    },

    // repo-hardlink option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-hardlink",
        .val = PARSE_OPTION_FLAG | cfgOptRepoHardlink,
    },
    {
        .name = "no-repo1-hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoHardlink,
    },
    {
        .name = "reset-repo1-hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHardlink,
    },
    {
        .name = "hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHardlink,
    },
    {
        .name = "no-hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoHardlink,
    },

    // repo-host option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHost,
    },
    {
        .name = "reset-repo1-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHost,
    },
    {
        .name = "backup-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHost,
    },

    // repo-host-cmd option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostCmd,
    },
    {
        .name = "reset-repo1-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostCmd,
    },
    {
        .name = "backup-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHostCmd,
    },

    // repo-host-config option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostConfig,
    },
    {
        .name = "reset-repo1-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostConfig,
    },
    {
        .name = "backup-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHostConfig,
    },

    // repo-host-config-include-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-config-include-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostConfigIncludePath,
    },
    {
        .name = "reset-repo1-host-config-include-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostConfigIncludePath,
    },

    // repo-host-config-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-config-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostConfigPath,
    },
    {
        .name = "reset-repo1-host-config-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostConfigPath,
    },

    // repo-host-port option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostPort,
    },
    {
        .name = "reset-repo1-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostPort,
    },
    {
        .name = "backup-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHostPort,
    },

    // repo-host-user option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostUser,
    },
    {
        .name = "reset-repo1-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostUser,
    },
    {
        .name = "backup-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHostUser,
    },

    // repo-local option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-local",
        .val = PARSE_OPTION_FLAG | cfgOptRepoLocal,
    },
    {
        .name = "no-repo1-local",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoLocal,
    },
    {
        .name = "reset-repo1-local",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoLocal,
    },

    // repo-path option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoPath,
    },
    {
        .name = "reset-repo1-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoPath,
    },
    {
        .name = "repo-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoPath,
    },

    // repo-retention-archive option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-archive",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionArchive,
    },
    {
        .name = "reset-repo1-retention-archive",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionArchive,
    },
    {
        .name = "retention-archive",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoRetentionArchive,
    },

    // repo-retention-archive-type option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-archive-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionArchiveType,
    },
    {
        .name = "reset-repo1-retention-archive-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionArchiveType,
    },
    {
        .name = "retention-archive-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoRetentionArchiveType,
    },

    // repo-retention-diff option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-diff",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionDiff,
    },
    {
        .name = "reset-repo1-retention-diff",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionDiff,
    },
    {
        .name = "retention-diff",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoRetentionDiff,
    },

    // repo-retention-full option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-full",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionFull,
    },
    {
        .name = "reset-repo1-retention-full",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionFull,
    },
    {
        .name = "retention-full",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoRetentionFull,
    },

    // repo-retention-full-type option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-full-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionFullType,
    },
    {
        .name = "reset-repo1-retention-full-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionFullType,
    },

    // repo-s3-bucket option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-bucket",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Bucket,
    },
    {
        .name = "reset-repo1-s3-bucket",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Bucket,
    },
    {
        .name = "repo-s3-bucket",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Bucket,
    },

    // repo-s3-ca-file option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-ca-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3CaFile,
    },
    {
        .name = "reset-repo1-s3-ca-file",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3CaFile,
    },
    {
        .name = "repo-s3-ca-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3CaFile,
    },

    // repo-s3-ca-path option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-ca-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3CaPath,
    },
    {
        .name = "reset-repo1-s3-ca-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3CaPath,
    },
    {
        .name = "repo-s3-ca-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3CaPath,
    },

    // repo-s3-endpoint option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-endpoint",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Endpoint,
    },
    {
        .name = "reset-repo1-s3-endpoint",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Endpoint,
    },
    {
        .name = "repo-s3-endpoint",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Endpoint,
    },

    // repo-s3-host option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Host,
    },
    {
        .name = "reset-repo1-s3-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Host,
    },
    {
        .name = "repo-s3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Host,
    },

    // repo-s3-key option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-key",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Key,
    },
    {
        .name = "reset-repo1-s3-key",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Key,
    },
    {
        .name = "repo-s3-key",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Key,
    },

    // repo-s3-key-secret option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-key-secret",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3KeySecret,
    },
    {
        .name = "reset-repo1-s3-key-secret",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3KeySecret,
    },
    {
        .name = "repo-s3-key-secret",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3KeySecret,
    },

    // repo-s3-key-type option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-key-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3KeyType,
    },
    {
        .name = "reset-repo1-s3-key-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3KeyType,
    },

    // repo-s3-port option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Port,
    },
    {
        .name = "reset-repo1-s3-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Port,
    },

    // repo-s3-region option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-region",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Region,
    },
    {
        .name = "reset-repo1-s3-region",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Region,
    },
    {
        .name = "repo-s3-region",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Region,
    },

    // repo-s3-role option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-role",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Role,
    },
    {
        .name = "reset-repo1-s3-role",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Role,
    },

    // repo-s3-token option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-token",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Token,
    },
    {
        .name = "reset-repo1-s3-token",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Token,
    },

    // repo-s3-uri-style option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-uri-style",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3UriStyle,
    },
    {
        .name = "reset-repo1-s3-uri-style",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3UriStyle,
    },

    // repo-s3-verify-tls option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-verify-tls",
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3VerifyTls,
    },
    {
        .name = "no-repo1-s3-verify-tls",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3VerifyTls,
    },
    {
        .name = "reset-repo1-s3-verify-tls",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3VerifyTls,
    },
    {
        .name = "repo-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3VerifyTls,
    },
    {
        .name = "no-repo-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3VerifyTls,
    },
    {
        .name = "repo1-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3VerifyTls,
    },
    {
        .name = "no-repo1-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3VerifyTls,
    },

    // repo-type option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoType,
    },
    {
        .name = "reset-repo1-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoType,
    },
    {
        .name = "repo-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoType,
    },

    // resume option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "resume",
        .val = PARSE_OPTION_FLAG | cfgOptResume,
    },
    {
        .name = "no-resume",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptResume,
    },
    {
        .name = "reset-resume",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptResume,
    },

    // sck-block option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "sck-block",
        .val = PARSE_OPTION_FLAG | cfgOptSckBlock,
    },
    {
        .name = "no-sck-block",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptSckBlock,
    },
    {
        .name = "reset-sck-block",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptSckBlock,
    },

    // sck-keep-alive option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "sck-keep-alive",
        .val = PARSE_OPTION_FLAG | cfgOptSckKeepAlive,
    },
    {
        .name = "no-sck-keep-alive",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptSckKeepAlive,
    },
    {
        .name = "reset-sck-keep-alive",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptSckKeepAlive,
    },

    // set option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "set",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptSet,
    },

    // sort option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "sort",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptSort,
    },

    // spool-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "spool-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptSpoolPath,
    },
    {
        .name = "reset-spool-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptSpoolPath,
    },

    // stanza option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "stanza",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptStanza,
    },

    // start-fast option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "start-fast",
        .val = PARSE_OPTION_FLAG | cfgOptStartFast,
    },
    {
        .name = "no-start-fast",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptStartFast,
    },
    {
        .name = "reset-start-fast",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptStartFast,
    },

    // stop-auto option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "stop-auto",
        .val = PARSE_OPTION_FLAG | cfgOptStopAuto,
    },
    {
        .name = "no-stop-auto",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptStopAuto,
    },
    {
        .name = "reset-stop-auto",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptStopAuto,
    },

    // tablespace-map option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "tablespace-map",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTablespaceMap,
    },
    {
        .name = "reset-tablespace-map",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptTablespaceMap,
    },

    // tablespace-map-all option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "tablespace-map-all",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTablespaceMapAll,
    },
    {
        .name = "reset-tablespace-map-all",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptTablespaceMapAll,
    },

    // target option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "target",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTarget,
    },

    // target-action option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "target-action",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTargetAction,
    },

    // target-exclusive option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "target-exclusive",
        .val = PARSE_OPTION_FLAG | cfgOptTargetExclusive,
    },

    // target-timeline option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "target-timeline",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTargetTimeline,
    },

    // tcp-keep-alive-count option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "tcp-keep-alive-count",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTcpKeepAliveCount,
    },
    {
        .name = "reset-tcp-keep-alive-count",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptTcpKeepAliveCount,
    },

    // tcp-keep-alive-idle option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "tcp-keep-alive-idle",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTcpKeepAliveIdle,
    },
    {
        .name = "reset-tcp-keep-alive-idle",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptTcpKeepAliveIdle,
    },

    // tcp-keep-alive-interval option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "tcp-keep-alive-interval",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTcpKeepAliveInterval,
    },
    {
        .name = "reset-tcp-keep-alive-interval",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptTcpKeepAliveInterval,
    },

    // type option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptType,
    },
    // Terminate option list
    {
        .name = NULL
    }
};

/***********************************************************************************************************************************
Order for option parse resolution
***********************************************************************************************************************************/
static const ConfigOption optionResolveOrder[] =
{
    cfgOptStanza,
    cfgOptArchiveAsync,
    cfgOptArchiveGetQueueMax,
    cfgOptArchiveMode,
    cfgOptArchivePushQueueMax,
    cfgOptArchiveTimeout,
    cfgOptBackupStandby,
    cfgOptBufferSize,
    cfgOptChecksumPage,
    cfgOptCipherPass,
    cfgOptCmdSsh,
    cfgOptCompress,
    cfgOptCompressLevel,
    cfgOptCompressLevelNetwork,
    cfgOptCompressType,
    cfgOptConfig,
    cfgOptConfigIncludePath,
    cfgOptConfigPath,
    cfgOptDbInclude,
    cfgOptDbTimeout,
    cfgOptDelta,
    cfgOptDryRun,
    cfgOptExclude,
    cfgOptExpireAuto,
    cfgOptFilter,
    cfgOptHostId,
    cfgOptIgnoreMissing,
    cfgOptIoTimeout,
    cfgOptLinkAll,
    cfgOptLinkMap,
    cfgOptLockPath,
    cfgOptLogLevelConsole,
    cfgOptLogLevelFile,
    cfgOptLogLevelStderr,
    cfgOptLogPath,
    cfgOptLogSubprocess,
    cfgOptLogTimestamp,
    cfgOptManifestSaveThreshold,
    cfgOptNeutralUmask,
    cfgOptOnline,
    cfgOptOutput,
    cfgOptPgLocal,
    cfgOptPgLocal + 1,
    cfgOptPgLocal + 2,
    cfgOptPgLocal + 3,
    cfgOptPgLocal + 4,
    cfgOptPgLocal + 5,
    cfgOptPgLocal + 6,
    cfgOptPgLocal + 7,
    cfgOptPgPath,
    cfgOptPgPath + 1,
    cfgOptPgPath + 2,
    cfgOptPgPath + 3,
    cfgOptPgPath + 4,
    cfgOptPgPath + 5,
    cfgOptPgPath + 6,
    cfgOptPgPath + 7,
    cfgOptPgPort,
    cfgOptPgPort + 1,
    cfgOptPgPort + 2,
    cfgOptPgPort + 3,
    cfgOptPgPort + 4,
    cfgOptPgPort + 5,
    cfgOptPgPort + 6,
    cfgOptPgPort + 7,
    cfgOptPgSocketPath,
    cfgOptPgSocketPath + 1,
    cfgOptPgSocketPath + 2,
    cfgOptPgSocketPath + 3,
    cfgOptPgSocketPath + 4,
    cfgOptPgSocketPath + 5,
    cfgOptPgSocketPath + 6,
    cfgOptPgSocketPath + 7,
    cfgOptPgUser,
    cfgOptPgUser + 1,
    cfgOptPgUser + 2,
    cfgOptPgUser + 3,
    cfgOptPgUser + 4,
    cfgOptPgUser + 5,
    cfgOptPgUser + 6,
    cfgOptPgUser + 7,
    cfgOptProcess,
    cfgOptProcessMax,
    cfgOptProtocolTimeout,
    cfgOptRaw,
    cfgOptRecurse,
    cfgOptRemoteType,
    cfgOptRepoCipherType,
    cfgOptRepoHardlink,
    cfgOptRepoLocal,
    cfgOptRepoPath,
    cfgOptRepoRetentionArchive,
    cfgOptRepoRetentionArchiveType,
    cfgOptRepoRetentionDiff,
    cfgOptRepoRetentionFull,
    cfgOptRepoRetentionFullType,
    cfgOptRepoType,
    cfgOptResume,
    cfgOptSckBlock,
    cfgOptSckKeepAlive,
    cfgOptSet,
    cfgOptSort,
    cfgOptSpoolPath,
    cfgOptStartFast,
    cfgOptStopAuto,
    cfgOptTablespaceMap,
    cfgOptTablespaceMapAll,
    cfgOptTcpKeepAliveCount,
    cfgOptTcpKeepAliveIdle,
    cfgOptTcpKeepAliveInterval,
    cfgOptType,
    cfgOptArchiveCheck,
    cfgOptArchiveCopy,
    cfgOptForce,
    cfgOptPgHost,
    cfgOptPgHost + 1,
    cfgOptPgHost + 2,
    cfgOptPgHost + 3,
    cfgOptPgHost + 4,
    cfgOptPgHost + 5,
    cfgOptPgHost + 6,
    cfgOptPgHost + 7,
    cfgOptPgHostCmd,
    cfgOptPgHostCmd + 1,
    cfgOptPgHostCmd + 2,
    cfgOptPgHostCmd + 3,
    cfgOptPgHostCmd + 4,
    cfgOptPgHostCmd + 5,
    cfgOptPgHostCmd + 6,
    cfgOptPgHostCmd + 7,
    cfgOptPgHostConfig,
    cfgOptPgHostConfig + 1,
    cfgOptPgHostConfig + 2,
    cfgOptPgHostConfig + 3,
    cfgOptPgHostConfig + 4,
    cfgOptPgHostConfig + 5,
    cfgOptPgHostConfig + 6,
    cfgOptPgHostConfig + 7,
    cfgOptPgHostConfigIncludePath,
    cfgOptPgHostConfigIncludePath + 1,
    cfgOptPgHostConfigIncludePath + 2,
    cfgOptPgHostConfigIncludePath + 3,
    cfgOptPgHostConfigIncludePath + 4,
    cfgOptPgHostConfigIncludePath + 5,
    cfgOptPgHostConfigIncludePath + 6,
    cfgOptPgHostConfigIncludePath + 7,
    cfgOptPgHostConfigPath,
    cfgOptPgHostConfigPath + 1,
    cfgOptPgHostConfigPath + 2,
    cfgOptPgHostConfigPath + 3,
    cfgOptPgHostConfigPath + 4,
    cfgOptPgHostConfigPath + 5,
    cfgOptPgHostConfigPath + 6,
    cfgOptPgHostConfigPath + 7,
    cfgOptPgHostPort,
    cfgOptPgHostPort + 1,
    cfgOptPgHostPort + 2,
    cfgOptPgHostPort + 3,
    cfgOptPgHostPort + 4,
    cfgOptPgHostPort + 5,
    cfgOptPgHostPort + 6,
    cfgOptPgHostPort + 7,
    cfgOptPgHostUser,
    cfgOptPgHostUser + 1,
    cfgOptPgHostUser + 2,
    cfgOptPgHostUser + 3,
    cfgOptPgHostUser + 4,
    cfgOptPgHostUser + 5,
    cfgOptPgHostUser + 6,
    cfgOptPgHostUser + 7,
    cfgOptRecoveryOption,
    cfgOptRepoAzureAccount,
    cfgOptRepoAzureCaFile,
    cfgOptRepoAzureCaPath,
    cfgOptRepoAzureContainer,
    cfgOptRepoAzureEndpoint,
    cfgOptRepoAzureHost,
    cfgOptRepoAzureKey,
    cfgOptRepoAzureKeyType,
    cfgOptRepoAzurePort,
    cfgOptRepoAzureVerifyTls,
    cfgOptRepoCipherPass,
    cfgOptRepoHost,
    cfgOptRepoHostCmd,
    cfgOptRepoHostConfig,
    cfgOptRepoHostConfigIncludePath,
    cfgOptRepoHostConfigPath,
    cfgOptRepoHostPort,
    cfgOptRepoHostUser,
    cfgOptRepoS3Bucket,
    cfgOptRepoS3CaFile,
    cfgOptRepoS3CaPath,
    cfgOptRepoS3Endpoint,
    cfgOptRepoS3Host,
    cfgOptRepoS3KeyType,
    cfgOptRepoS3Port,
    cfgOptRepoS3Region,
    cfgOptRepoS3Role,
    cfgOptRepoS3Token,
    cfgOptRepoS3UriStyle,
    cfgOptRepoS3VerifyTls,
    cfgOptTarget,
    cfgOptTargetAction,
    cfgOptTargetExclusive,
    cfgOptTargetTimeline,
    cfgOptRepoS3Key,
    cfgOptRepoS3KeySecret,
};
