/***********************************************************************************************************************************
Option Parse Definition

Automatically generated by Build.pm -- do not modify directly.
***********************************************************************************************************************************/

/***********************************************************************************************************************************
Option parse data
***********************************************************************************************************************************/
static const struct option optionList[] =
{
    {
        .name = "archive-async",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveAsync,
    },
    {
        .name = "no-archive-async",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveAsync,
    },
    {
        .name = "archive-check",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveCheck,
    },
    {
        .name = "no-archive-check",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveCheck,
    },
    {
        .name = "archive-copy",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveCopy,
    },
    {
        .name = "no-archive-copy",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveCopy,
    },
    {
        .name = "archive-queue-max",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptArchiveQueueMax,
    },
    {
        .name = "no-archive-queue-max",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveQueueMax,
    },
    {
        .name = "archive-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptArchiveTimeout,
    },
    {
        .name = "no-archive-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveTimeout,
    },
    {
        .name = "backup-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptBackupCmd,
    },
    {
        .name = "no-backup-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBackupCmd,
    },
    {
        .name = "backup-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptBackupConfig,
    },
    {
        .name = "no-backup-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBackupConfig,
    },
    {
        .name = "backup-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptBackupHost,
    },
    {
        .name = "no-backup-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBackupHost,
    },
    {
        .name = "backup-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptBackupSshPort,
    },
    {
        .name = "no-backup-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBackupSshPort,
    },
    {
        .name = "backup-standby",
        .val = PARSE_OPTION_FLAG | cfgOptBackupStandby,
    },
    {
        .name = "no-backup-standby",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBackupStandby,
    },
    {
        .name = "backup-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptBackupUser,
    },
    {
        .name = "no-backup-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBackupUser,
    },
    {
        .name = "buffer-size",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptBufferSize,
    },
    {
        .name = "no-buffer-size",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBufferSize,
    },
    {
        .name = "checksum-page",
        .val = PARSE_OPTION_FLAG | cfgOptChecksumPage,
    },
    {
        .name = "no-checksum-page",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptChecksumPage,
    },
    {
        .name = "cmd-ssh",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCmdSsh,
    },
    {
        .name = "no-cmd-ssh",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptCmdSsh,
    },
    {
        .name = "command",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCommand,
    },
    {
        .name = "compress",
        .val = PARSE_OPTION_FLAG | cfgOptCompress,
    },
    {
        .name = "no-compress",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptCompress,
    },
    {
        .name = "compress-level",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCompressLevel,
    },
    {
        .name = "no-compress-level",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptCompressLevel,
    },
    {
        .name = "compress-level-network",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCompressLevelNetwork,
    },
    {
        .name = "no-compress-level-network",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptCompressLevelNetwork,
    },
    {
        .name = "config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptConfig,
    },
    {
        .name = "no-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptConfig,
    },
    {
        .name = "db-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbCmd,
    },
    {
        .name = "no-db-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbCmd,
    },
    {
        .name = "db1-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbCmd,
    },
    {
        .name = "no-db1-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbCmd,
    },
    {
        .name = "db2-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbCmd + 1),
    },
    {
        .name = "no-db2-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbCmd + 1),
    },
    {
        .name = "db3-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbCmd + 2),
    },
    {
        .name = "no-db3-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbCmd + 2),
    },
    {
        .name = "db4-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbCmd + 3),
    },
    {
        .name = "no-db4-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbCmd + 3),
    },
    {
        .name = "db5-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbCmd + 4),
    },
    {
        .name = "no-db5-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbCmd + 4),
    },
    {
        .name = "db6-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbCmd + 5),
    },
    {
        .name = "no-db6-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbCmd + 5),
    },
    {
        .name = "db7-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbCmd + 6),
    },
    {
        .name = "no-db7-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbCmd + 6),
    },
    {
        .name = "db8-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbCmd + 7),
    },
    {
        .name = "no-db8-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbCmd + 7),
    },
    {
        .name = "db-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbConfig,
    },
    {
        .name = "no-db-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbConfig,
    },
    {
        .name = "db1-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbConfig,
    },
    {
        .name = "no-db1-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbConfig,
    },
    {
        .name = "db2-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbConfig + 1),
    },
    {
        .name = "no-db2-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbConfig + 1),
    },
    {
        .name = "db3-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbConfig + 2),
    },
    {
        .name = "no-db3-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbConfig + 2),
    },
    {
        .name = "db4-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbConfig + 3),
    },
    {
        .name = "no-db4-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbConfig + 3),
    },
    {
        .name = "db5-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbConfig + 4),
    },
    {
        .name = "no-db5-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbConfig + 4),
    },
    {
        .name = "db6-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbConfig + 5),
    },
    {
        .name = "no-db6-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbConfig + 5),
    },
    {
        .name = "db7-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbConfig + 6),
    },
    {
        .name = "no-db7-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbConfig + 6),
    },
    {
        .name = "db8-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbConfig + 7),
    },
    {
        .name = "no-db8-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbConfig + 7),
    },
    {
        .name = "db-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbHost,
    },
    {
        .name = "no-db-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbHost,
    },
    {
        .name = "db1-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbHost,
    },
    {
        .name = "no-db1-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbHost,
    },
    {
        .name = "db2-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbHost + 1),
    },
    {
        .name = "no-db2-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbHost + 1),
    },
    {
        .name = "db3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbHost + 2),
    },
    {
        .name = "no-db3-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbHost + 2),
    },
    {
        .name = "db4-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbHost + 3),
    },
    {
        .name = "no-db4-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbHost + 3),
    },
    {
        .name = "db5-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbHost + 4),
    },
    {
        .name = "no-db5-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbHost + 4),
    },
    {
        .name = "db6-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbHost + 5),
    },
    {
        .name = "no-db6-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbHost + 5),
    },
    {
        .name = "db7-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbHost + 6),
    },
    {
        .name = "no-db7-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbHost + 6),
    },
    {
        .name = "db8-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbHost + 7),
    },
    {
        .name = "no-db8-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbHost + 7),
    },
    {
        .name = "db-include",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbInclude,
    },
    {
        .name = "no-db-include",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbInclude,
    },
    {
        .name = "db-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbPath,
    },
    {
        .name = "no-db-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbPath,
    },
    {
        .name = "db1-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbPath,
    },
    {
        .name = "no-db1-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbPath,
    },
    {
        .name = "db2-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPath + 1),
    },
    {
        .name = "no-db2-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPath + 1),
    },
    {
        .name = "db3-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPath + 2),
    },
    {
        .name = "no-db3-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPath + 2),
    },
    {
        .name = "db4-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPath + 3),
    },
    {
        .name = "no-db4-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPath + 3),
    },
    {
        .name = "db5-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPath + 4),
    },
    {
        .name = "no-db5-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPath + 4),
    },
    {
        .name = "db6-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPath + 5),
    },
    {
        .name = "no-db6-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPath + 5),
    },
    {
        .name = "db7-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPath + 6),
    },
    {
        .name = "no-db7-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPath + 6),
    },
    {
        .name = "db8-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPath + 7),
    },
    {
        .name = "no-db8-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPath + 7),
    },
    {
        .name = "db-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbPort,
    },
    {
        .name = "no-db-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbPort,
    },
    {
        .name = "db1-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbPort,
    },
    {
        .name = "no-db1-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbPort,
    },
    {
        .name = "db2-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPort + 1),
    },
    {
        .name = "no-db2-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPort + 1),
    },
    {
        .name = "db3-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPort + 2),
    },
    {
        .name = "no-db3-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPort + 2),
    },
    {
        .name = "db4-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPort + 3),
    },
    {
        .name = "no-db4-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPort + 3),
    },
    {
        .name = "db5-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPort + 4),
    },
    {
        .name = "no-db5-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPort + 4),
    },
    {
        .name = "db6-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPort + 5),
    },
    {
        .name = "no-db6-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPort + 5),
    },
    {
        .name = "db7-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPort + 6),
    },
    {
        .name = "no-db7-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPort + 6),
    },
    {
        .name = "db8-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbPort + 7),
    },
    {
        .name = "no-db8-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbPort + 7),
    },
    {
        .name = "db-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbSocketPath,
    },
    {
        .name = "no-db-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbSocketPath,
    },
    {
        .name = "db1-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbSocketPath,
    },
    {
        .name = "no-db1-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbSocketPath,
    },
    {
        .name = "db2-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSocketPath + 1),
    },
    {
        .name = "no-db2-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSocketPath + 1),
    },
    {
        .name = "db3-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSocketPath + 2),
    },
    {
        .name = "no-db3-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSocketPath + 2),
    },
    {
        .name = "db4-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSocketPath + 3),
    },
    {
        .name = "no-db4-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSocketPath + 3),
    },
    {
        .name = "db5-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSocketPath + 4),
    },
    {
        .name = "no-db5-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSocketPath + 4),
    },
    {
        .name = "db6-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSocketPath + 5),
    },
    {
        .name = "no-db6-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSocketPath + 5),
    },
    {
        .name = "db7-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSocketPath + 6),
    },
    {
        .name = "no-db7-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSocketPath + 6),
    },
    {
        .name = "db8-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSocketPath + 7),
    },
    {
        .name = "no-db8-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSocketPath + 7),
    },
    {
        .name = "db-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbSshPort,
    },
    {
        .name = "no-db-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbSshPort,
    },
    {
        .name = "db1-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbSshPort,
    },
    {
        .name = "no-db1-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbSshPort,
    },
    {
        .name = "db2-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSshPort + 1),
    },
    {
        .name = "no-db2-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSshPort + 1),
    },
    {
        .name = "db3-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSshPort + 2),
    },
    {
        .name = "no-db3-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSshPort + 2),
    },
    {
        .name = "db4-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSshPort + 3),
    },
    {
        .name = "no-db4-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSshPort + 3),
    },
    {
        .name = "db5-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSshPort + 4),
    },
    {
        .name = "no-db5-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSshPort + 4),
    },
    {
        .name = "db6-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSshPort + 5),
    },
    {
        .name = "no-db6-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSshPort + 5),
    },
    {
        .name = "db7-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSshPort + 6),
    },
    {
        .name = "no-db7-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSshPort + 6),
    },
    {
        .name = "db8-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbSshPort + 7),
    },
    {
        .name = "no-db8-ssh-port",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbSshPort + 7),
    },
    {
        .name = "db-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbTimeout,
    },
    {
        .name = "no-db-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbTimeout,
    },
    {
        .name = "db-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbUser,
    },
    {
        .name = "no-db-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbUser,
    },
    {
        .name = "db1-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbUser,
    },
    {
        .name = "no-db1-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptDbUser,
    },
    {
        .name = "db2-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbUser + 1),
    },
    {
        .name = "no-db2-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbUser + 1),
    },
    {
        .name = "db3-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbUser + 2),
    },
    {
        .name = "no-db3-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbUser + 2),
    },
    {
        .name = "db4-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbUser + 3),
    },
    {
        .name = "no-db4-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbUser + 3),
    },
    {
        .name = "db5-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbUser + 4),
    },
    {
        .name = "no-db5-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbUser + 4),
    },
    {
        .name = "db6-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbUser + 5),
    },
    {
        .name = "no-db6-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbUser + 5),
    },
    {
        .name = "db7-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbUser + 6),
    },
    {
        .name = "no-db7-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbUser + 6),
    },
    {
        .name = "db8-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptDbUser + 7),
    },
    {
        .name = "no-db8-user",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | (cfgOptDbUser + 7),
    },
    {
        .name = "delta",
        .val = PARSE_OPTION_FLAG | cfgOptDelta,
    },
    {
        .name = "force",
        .val = PARSE_OPTION_FLAG | cfgOptForce,
    },
    {
        .name = "hardlink",
        .val = PARSE_OPTION_FLAG | cfgOptHardlink,
    },
    {
        .name = "no-hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptHardlink,
    },
    {
        .name = "host-id",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptHostId,
    },
    {
        .name = "link-all",
        .val = PARSE_OPTION_FLAG | cfgOptLinkAll,
    },
    {
        .name = "no-link-all",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLinkAll,
    },
    {
        .name = "link-map",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLinkMap,
    },
    {
        .name = "no-link-map",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLinkMap,
    },
    {
        .name = "lock-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLockPath,
    },
    {
        .name = "no-lock-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLockPath,
    },
    {
        .name = "log-level-console",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelConsole,
    },
    {
        .name = "no-log-level-console",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLogLevelConsole,
    },
    {
        .name = "log-level-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelFile,
    },
    {
        .name = "no-log-level-file",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLogLevelFile,
    },
    {
        .name = "log-level-stderr",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelStderr,
    },
    {
        .name = "no-log-level-stderr",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLogLevelStderr,
    },
    {
        .name = "log-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogPath,
    },
    {
        .name = "no-log-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLogPath,
    },
    {
        .name = "log-timestamp",
        .val = PARSE_OPTION_FLAG | cfgOptLogTimestamp,
    },
    {
        .name = "no-log-timestamp",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLogTimestamp,
    },
    {
        .name = "manifest-save-threshold",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptManifestSaveThreshold,
    },
    {
        .name = "no-manifest-save-threshold",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptManifestSaveThreshold,
    },
    {
        .name = "neutral-umask",
        .val = PARSE_OPTION_FLAG | cfgOptNeutralUmask,
    },
    {
        .name = "no-neutral-umask",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptNeutralUmask,
    },
    {
        .name = "online",
        .val = PARSE_OPTION_FLAG | cfgOptOnline,
    },
    {
        .name = "no-online",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptOnline,
    },
    {
        .name = "output",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptOutput,
    },
    {
        .name = "perl-option",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPerlOption,
    },
    {
        .name = "no-perl-option",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptPerlOption,
    },
    {
        .name = "process",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProcess,
    },
    {
        .name = "process-max",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProcessMax,
    },
    {
        .name = "no-process-max",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptProcessMax,
    },
    {
        .name = "protocol-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProtocolTimeout,
    },
    {
        .name = "no-protocol-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptProtocolTimeout,
    },
    {
        .name = "recovery-option",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRecoveryOption,
    },
    {
        .name = "no-recovery-option",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRecoveryOption,
    },
    {
        .name = "repo-cipher-pass",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoCipherPass,
    },
    {
        .name = "no-repo-cipher-pass",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoCipherPass,
    },
    {
        .name = "repo-cipher-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoCipherType,
    },
    {
        .name = "no-repo-cipher-type",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoCipherType,
    },
    {
        .name = "repo-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoPath,
    },
    {
        .name = "no-repo-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoPath,
    },
    {
        .name = "repo-s3-bucket",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Bucket,
    },
    {
        .name = "no-repo-s3-bucket",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3Bucket,
    },
    {
        .name = "repo-s3-ca-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3CaFile,
    },
    {
        .name = "no-repo-s3-ca-file",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3CaFile,
    },
    {
        .name = "repo-s3-ca-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3CaPath,
    },
    {
        .name = "no-repo-s3-ca-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3CaPath,
    },
    {
        .name = "repo-s3-endpoint",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Endpoint,
    },
    {
        .name = "no-repo-s3-endpoint",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3Endpoint,
    },
    {
        .name = "repo-s3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Host,
    },
    {
        .name = "no-repo-s3-host",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3Host,
    },
    {
        .name = "repo-s3-key",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Key,
    },
    {
        .name = "no-repo-s3-key",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3Key,
    },
    {
        .name = "repo-s3-key-secret",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3KeySecret,
    },
    {
        .name = "no-repo-s3-key-secret",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3KeySecret,
    },
    {
        .name = "repo-s3-region",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Region,
    },
    {
        .name = "no-repo-s3-region",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3Region,
    },
    {
        .name = "repo-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3VerifySsl,
    },
    {
        .name = "no-repo-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3VerifySsl,
    },
    {
        .name = "repo-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoType,
    },
    {
        .name = "no-repo-type",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoType,
    },
    {
        .name = "resume",
        .val = PARSE_OPTION_FLAG | cfgOptResume,
    },
    {
        .name = "no-resume",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptResume,
    },
    {
        .name = "retention-archive",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRetentionArchive,
    },
    {
        .name = "no-retention-archive",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRetentionArchive,
    },
    {
        .name = "retention-archive-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRetentionArchiveType,
    },
    {
        .name = "no-retention-archive-type",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRetentionArchiveType,
    },
    {
        .name = "retention-diff",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRetentionDiff,
    },
    {
        .name = "no-retention-diff",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRetentionDiff,
    },
    {
        .name = "retention-full",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRetentionFull,
    },
    {
        .name = "no-retention-full",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRetentionFull,
    },
    {
        .name = "set",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptSet,
    },
    {
        .name = "spool-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptSpoolPath,
    },
    {
        .name = "no-spool-path",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptSpoolPath,
    },
    {
        .name = "stanza",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptStanza,
    },
    {
        .name = "start-fast",
        .val = PARSE_OPTION_FLAG | cfgOptStartFast,
    },
    {
        .name = "no-start-fast",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptStartFast,
    },
    {
        .name = "stop-auto",
        .val = PARSE_OPTION_FLAG | cfgOptStopAuto,
    },
    {
        .name = "no-stop-auto",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptStopAuto,
    },
    {
        .name = "tablespace-map",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTablespaceMap,
    },
    {
        .name = "no-tablespace-map",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptTablespaceMap,
    },
    {
        .name = "tablespace-map-all",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTablespaceMapAll,
    },
    {
        .name = "no-tablespace-map-all",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptTablespaceMapAll,
    },
    {
        .name = "target",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTarget,
    },
    {
        .name = "target-action",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTargetAction,
    },
    {
        .name = "target-exclusive",
        .val = PARSE_OPTION_FLAG | cfgOptTargetExclusive,
    },
    {
        .name = "target-timeline",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTargetTimeline,
    },
    {
        .name = "test",
        .val = PARSE_OPTION_FLAG | cfgOptTest,
    },
    {
        .name = "test-delay",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTestDelay,
    },
    {
        .name = "test-point",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTestPoint,
    },
    {
        .name = "type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptType,
    },
    // Terminate option list
    {
        .name = NULL
    }
};
