/***********************************************************************************************************************************
Config Parse Rules

Automatically generated by Build.pm -- do not modify directly.
***********************************************************************************************************************************/
#ifndef CONFIG_PARSE_AUTO_H
#define CONFIG_PARSE_AUTO_H

/***********************************************************************************************************************************
Option type enum
***********************************************************************************************************************************/
typedef enum
{
    cfgOptTypeBoolean,
    cfgOptTypeHash,
    cfgOptTypeInteger,
    cfgOptTypeList,
    cfgOptTypePath,
    cfgOptTypeSize,
    cfgOptTypeString,
    cfgOptTypeTime,
} ConfigOptionType;

#endif
