/***********************************************************************************************************************************
Option Parse Definition

Automatically generated by Build.pm -- do not modify directly.
***********************************************************************************************************************************/

/***********************************************************************************************************************************
Option parse data
***********************************************************************************************************************************/
static const struct option optionList[] =
{
    // archive-async option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-async",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveAsync,
    },
    {
        .name = "no-archive-async",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveAsync,
    },
    {
        .name = "reset-archive-async",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveAsync,
    },

    // archive-check option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-check",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveCheck,
    },
    {
        .name = "no-archive-check",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveCheck,
    },
    {
        .name = "reset-archive-check",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveCheck,
    },

    // archive-copy option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-copy",
        .val = PARSE_OPTION_FLAG | cfgOptArchiveCopy,
    },
    {
        .name = "no-archive-copy",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptArchiveCopy,
    },
    {
        .name = "reset-archive-copy",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveCopy,
    },

    // archive-queue-max option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-queue-max",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptArchiveQueueMax,
    },
    {
        .name = "reset-archive-queue-max",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveQueueMax,
    },

    // archive-timeout option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "archive-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptArchiveTimeout,
    },
    {
        .name = "reset-archive-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptArchiveTimeout,
    },

    // backup-standby option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "backup-standby",
        .val = PARSE_OPTION_FLAG | cfgOptBackupStandby,
    },
    {
        .name = "no-backup-standby",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptBackupStandby,
    },
    {
        .name = "reset-backup-standby",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptBackupStandby,
    },

    // buffer-size option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "buffer-size",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptBufferSize,
    },
    {
        .name = "reset-buffer-size",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptBufferSize,
    },

    // checksum-page option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "checksum-page",
        .val = PARSE_OPTION_FLAG | cfgOptChecksumPage,
    },
    {
        .name = "no-checksum-page",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptChecksumPage,
    },
    {
        .name = "reset-checksum-page",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptChecksumPage,
    },

    // cmd-ssh option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "cmd-ssh",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCmdSsh,
    },
    {
        .name = "reset-cmd-ssh",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCmdSsh,
    },

    // command option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "command",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCommand,
    },

    // compress option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "compress",
        .val = PARSE_OPTION_FLAG | cfgOptCompress,
    },
    {
        .name = "no-compress",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptCompress,
    },
    {
        .name = "reset-compress",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCompress,
    },

    // compress-level option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "compress-level",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCompressLevel,
    },
    {
        .name = "reset-compress-level",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCompressLevel,
    },

    // compress-level-network option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "compress-level-network",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptCompressLevelNetwork,
    },
    {
        .name = "reset-compress-level-network",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptCompressLevelNetwork,
    },

    // config option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptConfig,
    },
    {
        .name = "no-config",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptConfig,
    },

    // db-include option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "db-include",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbInclude,
    },
    {
        .name = "reset-db-include",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptDbInclude,
    },

    // db-timeout option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "db-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptDbTimeout,
    },
    {
        .name = "reset-db-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptDbTimeout,
    },

    // delta option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "delta",
        .val = PARSE_OPTION_FLAG | cfgOptDelta,
    },

    // force option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "force",
        .val = PARSE_OPTION_FLAG | cfgOptForce,
    },

    // host-id option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "host-id",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptHostId,
    },

    // link-all option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "link-all",
        .val = PARSE_OPTION_FLAG | cfgOptLinkAll,
    },
    {
        .name = "no-link-all",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLinkAll,
    },
    {
        .name = "reset-link-all",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLinkAll,
    },

    // link-map option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "link-map",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLinkMap,
    },
    {
        .name = "reset-link-map",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLinkMap,
    },

    // lock-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "lock-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLockPath,
    },
    {
        .name = "reset-lock-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLockPath,
    },

    // log-level-console option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-level-console",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelConsole,
    },
    {
        .name = "reset-log-level-console",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogLevelConsole,
    },

    // log-level-file option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-level-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelFile,
    },
    {
        .name = "reset-log-level-file",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogLevelFile,
    },

    // log-level-stderr option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-level-stderr",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogLevelStderr,
    },
    {
        .name = "reset-log-level-stderr",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogLevelStderr,
    },

    // log-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptLogPath,
    },
    {
        .name = "reset-log-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogPath,
    },

    // log-timestamp option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "log-timestamp",
        .val = PARSE_OPTION_FLAG | cfgOptLogTimestamp,
    },
    {
        .name = "no-log-timestamp",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptLogTimestamp,
    },
    {
        .name = "reset-log-timestamp",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptLogTimestamp,
    },

    // manifest-save-threshold option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "manifest-save-threshold",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptManifestSaveThreshold,
    },
    {
        .name = "reset-manifest-save-threshold",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptManifestSaveThreshold,
    },

    // neutral-umask option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "neutral-umask",
        .val = PARSE_OPTION_FLAG | cfgOptNeutralUmask,
    },
    {
        .name = "no-neutral-umask",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptNeutralUmask,
    },
    {
        .name = "reset-neutral-umask",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptNeutralUmask,
    },

    // online option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "online",
        .val = PARSE_OPTION_FLAG | cfgOptOnline,
    },
    {
        .name = "no-online",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptOnline,
    },

    // output option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "output",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptOutput,
    },

    // perl-option option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "perl-option",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPerlOption,
    },
    {
        .name = "reset-perl-option",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPerlOption,
    },

    // pg-host option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHost,
    },
    {
        .name = "reset-pg1-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHost,
    },
    {
        .name = "db-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHost,
    },
    {
        .name = "db1-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHost,
    },
    {
        .name = "pg2-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 1),
    },
    {
        .name = "reset-pg2-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 1),
    },
    {
        .name = "db2-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 1),
    },
    {
        .name = "pg3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 2),
    },
    {
        .name = "reset-pg3-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 2),
    },
    {
        .name = "db3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 2),
    },
    {
        .name = "pg4-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 3),
    },
    {
        .name = "reset-pg4-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 3),
    },
    {
        .name = "db4-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 3),
    },
    {
        .name = "pg5-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 4),
    },
    {
        .name = "reset-pg5-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 4),
    },
    {
        .name = "db5-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 4),
    },
    {
        .name = "pg6-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 5),
    },
    {
        .name = "reset-pg6-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 5),
    },
    {
        .name = "db6-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 5),
    },
    {
        .name = "pg7-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 6),
    },
    {
        .name = "reset-pg7-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 6),
    },
    {
        .name = "db7-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 6),
    },
    {
        .name = "pg8-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHost + 7),
    },
    {
        .name = "reset-pg8-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHost + 7),
    },
    {
        .name = "db8-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHost + 7),
    },

    // pg-host-cmd option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostCmd,
    },
    {
        .name = "reset-pg1-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostCmd,
    },
    {
        .name = "db-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostCmd,
    },
    {
        .name = "db1-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostCmd,
    },
    {
        .name = "pg2-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 1),
    },
    {
        .name = "reset-pg2-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 1),
    },
    {
        .name = "db2-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 1),
    },
    {
        .name = "pg3-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 2),
    },
    {
        .name = "reset-pg3-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 2),
    },
    {
        .name = "db3-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 2),
    },
    {
        .name = "pg4-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 3),
    },
    {
        .name = "reset-pg4-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 3),
    },
    {
        .name = "db4-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 3),
    },
    {
        .name = "pg5-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 4),
    },
    {
        .name = "reset-pg5-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 4),
    },
    {
        .name = "db5-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 4),
    },
    {
        .name = "pg6-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 5),
    },
    {
        .name = "reset-pg6-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 5),
    },
    {
        .name = "db6-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 5),
    },
    {
        .name = "pg7-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 6),
    },
    {
        .name = "reset-pg7-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 6),
    },
    {
        .name = "db7-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 6),
    },
    {
        .name = "pg8-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostCmd + 7),
    },
    {
        .name = "reset-pg8-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostCmd + 7),
    },
    {
        .name = "db8-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostCmd + 7),
    },

    // pg-host-config option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostConfig,
    },
    {
        .name = "reset-pg1-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostConfig,
    },
    {
        .name = "db-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostConfig,
    },
    {
        .name = "db1-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostConfig,
    },
    {
        .name = "pg2-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 1),
    },
    {
        .name = "reset-pg2-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 1),
    },
    {
        .name = "db2-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 1),
    },
    {
        .name = "pg3-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 2),
    },
    {
        .name = "reset-pg3-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 2),
    },
    {
        .name = "db3-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 2),
    },
    {
        .name = "pg4-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 3),
    },
    {
        .name = "reset-pg4-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 3),
    },
    {
        .name = "db4-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 3),
    },
    {
        .name = "pg5-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 4),
    },
    {
        .name = "reset-pg5-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 4),
    },
    {
        .name = "db5-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 4),
    },
    {
        .name = "pg6-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 5),
    },
    {
        .name = "reset-pg6-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 5),
    },
    {
        .name = "db6-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 5),
    },
    {
        .name = "pg7-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 6),
    },
    {
        .name = "reset-pg7-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 6),
    },
    {
        .name = "db7-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 6),
    },
    {
        .name = "pg8-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostConfig + 7),
    },
    {
        .name = "reset-pg8-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostConfig + 7),
    },
    {
        .name = "db8-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostConfig + 7),
    },

    // pg-host-port option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostPort,
    },
    {
        .name = "reset-pg1-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostPort,
    },
    {
        .name = "db-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostPort,
    },
    {
        .name = "db1-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostPort,
    },
    {
        .name = "pg2-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 1),
    },
    {
        .name = "reset-pg2-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 1),
    },
    {
        .name = "db2-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 1),
    },
    {
        .name = "pg3-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 2),
    },
    {
        .name = "reset-pg3-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 2),
    },
    {
        .name = "db3-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 2),
    },
    {
        .name = "pg4-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 3),
    },
    {
        .name = "reset-pg4-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 3),
    },
    {
        .name = "db4-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 3),
    },
    {
        .name = "pg5-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 4),
    },
    {
        .name = "reset-pg5-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 4),
    },
    {
        .name = "db5-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 4),
    },
    {
        .name = "pg6-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 5),
    },
    {
        .name = "reset-pg6-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 5),
    },
    {
        .name = "db6-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 5),
    },
    {
        .name = "pg7-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 6),
    },
    {
        .name = "reset-pg7-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 6),
    },
    {
        .name = "db7-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 6),
    },
    {
        .name = "pg8-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostPort + 7),
    },
    {
        .name = "reset-pg8-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostPort + 7),
    },
    {
        .name = "db8-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostPort + 7),
    },

    // pg-host-user option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgHostUser,
    },
    {
        .name = "reset-pg1-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgHostUser,
    },
    {
        .name = "db-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostUser,
    },
    {
        .name = "db1-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgHostUser,
    },
    {
        .name = "pg2-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 1),
    },
    {
        .name = "reset-pg2-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 1),
    },
    {
        .name = "db2-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 1),
    },
    {
        .name = "pg3-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 2),
    },
    {
        .name = "reset-pg3-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 2),
    },
    {
        .name = "db3-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 2),
    },
    {
        .name = "pg4-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 3),
    },
    {
        .name = "reset-pg4-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 3),
    },
    {
        .name = "db4-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 3),
    },
    {
        .name = "pg5-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 4),
    },
    {
        .name = "reset-pg5-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 4),
    },
    {
        .name = "db5-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 4),
    },
    {
        .name = "pg6-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 5),
    },
    {
        .name = "reset-pg6-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 5),
    },
    {
        .name = "db6-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 5),
    },
    {
        .name = "pg7-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 6),
    },
    {
        .name = "reset-pg7-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 6),
    },
    {
        .name = "db7-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 6),
    },
    {
        .name = "pg8-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgHostUser + 7),
    },
    {
        .name = "reset-pg8-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgHostUser + 7),
    },
    {
        .name = "db8-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgHostUser + 7),
    },

    // pg-path option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgPath,
    },
    {
        .name = "reset-pg1-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgPath,
    },
    {
        .name = "db-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgPath,
    },
    {
        .name = "db1-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgPath,
    },
    {
        .name = "pg2-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 1),
    },
    {
        .name = "reset-pg2-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 1),
    },
    {
        .name = "db2-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 1),
    },
    {
        .name = "pg3-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 2),
    },
    {
        .name = "reset-pg3-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 2),
    },
    {
        .name = "db3-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 2),
    },
    {
        .name = "pg4-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 3),
    },
    {
        .name = "reset-pg4-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 3),
    },
    {
        .name = "db4-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 3),
    },
    {
        .name = "pg5-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 4),
    },
    {
        .name = "reset-pg5-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 4),
    },
    {
        .name = "db5-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 4),
    },
    {
        .name = "pg6-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 5),
    },
    {
        .name = "reset-pg6-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 5),
    },
    {
        .name = "db6-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 5),
    },
    {
        .name = "pg7-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 6),
    },
    {
        .name = "reset-pg7-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 6),
    },
    {
        .name = "db7-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 6),
    },
    {
        .name = "pg8-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPath + 7),
    },
    {
        .name = "reset-pg8-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPath + 7),
    },
    {
        .name = "db8-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPath + 7),
    },

    // pg-port option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgPort,
    },
    {
        .name = "reset-pg1-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgPort,
    },
    {
        .name = "db-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgPort,
    },
    {
        .name = "db1-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgPort,
    },
    {
        .name = "pg2-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 1),
    },
    {
        .name = "reset-pg2-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 1),
    },
    {
        .name = "db2-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 1),
    },
    {
        .name = "pg3-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 2),
    },
    {
        .name = "reset-pg3-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 2),
    },
    {
        .name = "db3-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 2),
    },
    {
        .name = "pg4-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 3),
    },
    {
        .name = "reset-pg4-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 3),
    },
    {
        .name = "db4-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 3),
    },
    {
        .name = "pg5-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 4),
    },
    {
        .name = "reset-pg5-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 4),
    },
    {
        .name = "db5-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 4),
    },
    {
        .name = "pg6-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 5),
    },
    {
        .name = "reset-pg6-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 5),
    },
    {
        .name = "db6-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 5),
    },
    {
        .name = "pg7-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 6),
    },
    {
        .name = "reset-pg7-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 6),
    },
    {
        .name = "db7-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 6),
    },
    {
        .name = "pg8-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgPort + 7),
    },
    {
        .name = "reset-pg8-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgPort + 7),
    },
    {
        .name = "db8-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgPort + 7),
    },

    // pg-socket-path option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "pg1-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptPgSocketPath,
    },
    {
        .name = "reset-pg1-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptPgSocketPath,
    },
    {
        .name = "db-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgSocketPath,
    },
    {
        .name = "db1-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptPgSocketPath,
    },
    {
        .name = "pg2-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 1),
    },
    {
        .name = "reset-pg2-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 1),
    },
    {
        .name = "db2-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 1),
    },
    {
        .name = "pg3-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 2),
    },
    {
        .name = "reset-pg3-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 2),
    },
    {
        .name = "db3-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 2),
    },
    {
        .name = "pg4-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 3),
    },
    {
        .name = "reset-pg4-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 3),
    },
    {
        .name = "db4-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 3),
    },
    {
        .name = "pg5-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 4),
    },
    {
        .name = "reset-pg5-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 4),
    },
    {
        .name = "db5-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 4),
    },
    {
        .name = "pg6-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 5),
    },
    {
        .name = "reset-pg6-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 5),
    },
    {
        .name = "db6-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 5),
    },
    {
        .name = "pg7-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 6),
    },
    {
        .name = "reset-pg7-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 6),
    },
    {
        .name = "db7-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 6),
    },
    {
        .name = "pg8-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | (cfgOptPgSocketPath + 7),
    },
    {
        .name = "reset-pg8-socket-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | (cfgOptPgSocketPath + 7),
    },
    {
        .name = "db8-socket-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | (cfgOptPgSocketPath + 7),
    },

    // process option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "process",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProcess,
    },

    // process-max option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "process-max",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProcessMax,
    },
    {
        .name = "reset-process-max",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptProcessMax,
    },

    // protocol-timeout option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "protocol-timeout",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptProtocolTimeout,
    },
    {
        .name = "reset-protocol-timeout",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptProtocolTimeout,
    },

    // recovery-option option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "recovery-option",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRecoveryOption,
    },
    {
        .name = "reset-recovery-option",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRecoveryOption,
    },

    // repo-cipher-pass option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-cipher-pass",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoCipherPass,
    },
    {
        .name = "reset-repo1-cipher-pass",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoCipherPass,
    },
    {
        .name = "repo-cipher-pass",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoCipherPass,
    },

    // repo-cipher-type option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-cipher-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoCipherType,
    },
    {
        .name = "reset-repo1-cipher-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoCipherType,
    },
    {
        .name = "repo-cipher-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoCipherType,
    },

    // repo-hardlink option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-hardlink",
        .val = PARSE_OPTION_FLAG | cfgOptRepoHardlink,
    },
    {
        .name = "no-repo1-hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoHardlink,
    },
    {
        .name = "reset-repo1-hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHardlink,
    },
    {
        .name = "hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHardlink,
    },
    {
        .name = "no-hardlink",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoHardlink,
    },

    // repo-host option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHost,
    },
    {
        .name = "reset-repo1-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHost,
    },
    {
        .name = "backup-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHost,
    },

    // repo-host-cmd option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostCmd,
    },
    {
        .name = "reset-repo1-host-cmd",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostCmd,
    },
    {
        .name = "backup-cmd",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHostCmd,
    },

    // repo-host-config option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostConfig,
    },
    {
        .name = "reset-repo1-host-config",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostConfig,
    },
    {
        .name = "backup-config",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHostConfig,
    },

    // repo-host-port option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostPort,
    },
    {
        .name = "reset-repo1-host-port",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostPort,
    },
    {
        .name = "backup-ssh-port",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHostPort,
    },

    // repo-host-user option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-host-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoHostUser,
    },
    {
        .name = "reset-repo1-host-user",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoHostUser,
    },
    {
        .name = "backup-user",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoHostUser,
    },

    // repo-path option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoPath,
    },
    {
        .name = "reset-repo1-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoPath,
    },
    {
        .name = "repo-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoPath,
    },

    // repo-retention-archive option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-archive",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionArchive,
    },
    {
        .name = "reset-repo1-retention-archive",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionArchive,
    },
    {
        .name = "retention-archive",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoRetentionArchive,
    },

    // repo-retention-archive-type option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-archive-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionArchiveType,
    },
    {
        .name = "reset-repo1-retention-archive-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionArchiveType,
    },
    {
        .name = "retention-archive-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoRetentionArchiveType,
    },

    // repo-retention-diff option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-diff",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionDiff,
    },
    {
        .name = "reset-repo1-retention-diff",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionDiff,
    },
    {
        .name = "retention-diff",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoRetentionDiff,
    },

    // repo-retention-full option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-retention-full",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoRetentionFull,
    },
    {
        .name = "reset-repo1-retention-full",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoRetentionFull,
    },
    {
        .name = "retention-full",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoRetentionFull,
    },

    // repo-s3-bucket option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-bucket",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Bucket,
    },
    {
        .name = "reset-repo1-s3-bucket",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Bucket,
    },
    {
        .name = "repo-s3-bucket",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Bucket,
    },

    // repo-s3-ca-file option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-ca-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3CaFile,
    },
    {
        .name = "reset-repo1-s3-ca-file",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3CaFile,
    },
    {
        .name = "repo-s3-ca-file",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3CaFile,
    },

    // repo-s3-ca-path option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-ca-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3CaPath,
    },
    {
        .name = "reset-repo1-s3-ca-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3CaPath,
    },
    {
        .name = "repo-s3-ca-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3CaPath,
    },

    // repo-s3-endpoint option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-endpoint",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Endpoint,
    },
    {
        .name = "reset-repo1-s3-endpoint",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Endpoint,
    },
    {
        .name = "repo-s3-endpoint",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Endpoint,
    },

    // repo-s3-host option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Host,
    },
    {
        .name = "reset-repo1-s3-host",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Host,
    },
    {
        .name = "repo-s3-host",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Host,
    },

    // repo-s3-key option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-key",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Key,
    },
    {
        .name = "reset-repo1-s3-key",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Key,
    },
    {
        .name = "repo-s3-key",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Key,
    },

    // repo-s3-key-secret option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-key-secret",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3KeySecret,
    },
    {
        .name = "reset-repo1-s3-key-secret",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3KeySecret,
    },
    {
        .name = "repo-s3-key-secret",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3KeySecret,
    },

    // repo-s3-region option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-region",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3Region,
    },
    {
        .name = "reset-repo1-s3-region",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3Region,
    },
    {
        .name = "repo-s3-region",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3Region,
    },

    // repo-s3-verify-ssl option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | cfgOptRepoS3VerifySsl,
    },
    {
        .name = "no-repo1-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3VerifySsl,
    },
    {
        .name = "reset-repo1-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoS3VerifySsl,
    },
    {
        .name = "repo-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoS3VerifySsl,
    },
    {
        .name = "no-repo-s3-verify-ssl",
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | PARSE_NEGATE_FLAG | cfgOptRepoS3VerifySsl,
    },

    // repo-type option and deprecations
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "repo1-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptRepoType,
    },
    {
        .name = "reset-repo1-type",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptRepoType,
    },
    {
        .name = "repo-type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | PARSE_DEPRECATE_FLAG | cfgOptRepoType,
    },

    // resume option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "resume",
        .val = PARSE_OPTION_FLAG | cfgOptResume,
    },
    {
        .name = "no-resume",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptResume,
    },
    {
        .name = "reset-resume",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptResume,
    },

    // set option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "set",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptSet,
    },

    // spool-path option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "spool-path",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptSpoolPath,
    },
    {
        .name = "reset-spool-path",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptSpoolPath,
    },

    // stanza option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "stanza",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptStanza,
    },

    // start-fast option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "start-fast",
        .val = PARSE_OPTION_FLAG | cfgOptStartFast,
    },
    {
        .name = "no-start-fast",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptStartFast,
    },
    {
        .name = "reset-start-fast",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptStartFast,
    },

    // stop-auto option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "stop-auto",
        .val = PARSE_OPTION_FLAG | cfgOptStopAuto,
    },
    {
        .name = "no-stop-auto",
        .val = PARSE_OPTION_FLAG | PARSE_NEGATE_FLAG | cfgOptStopAuto,
    },
    {
        .name = "reset-stop-auto",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptStopAuto,
    },

    // tablespace-map option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "tablespace-map",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTablespaceMap,
    },
    {
        .name = "reset-tablespace-map",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptTablespaceMap,
    },

    // tablespace-map-all option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "tablespace-map-all",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTablespaceMapAll,
    },
    {
        .name = "reset-tablespace-map-all",
        .val = PARSE_OPTION_FLAG | PARSE_RESET_FLAG | cfgOptTablespaceMapAll,
    },

    // target option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "target",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTarget,
    },

    // target-action option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "target-action",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTargetAction,
    },

    // target-exclusive option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "target-exclusive",
        .val = PARSE_OPTION_FLAG | cfgOptTargetExclusive,
    },

    // target-timeline option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "target-timeline",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTargetTimeline,
    },

    // test option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "test",
        .val = PARSE_OPTION_FLAG | cfgOptTest,
    },

    // test-delay option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "test-delay",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTestDelay,
    },

    // test-point option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "test-point",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptTestPoint,
    },

    // type option
    // -----------------------------------------------------------------------------------------------------------------------------
    {
        .name = "type",
        .has_arg = required_argument,
        .val = PARSE_OPTION_FLAG | cfgOptType,
    },
    // Terminate option list
    {
        .name = NULL
    }
};
